-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_mult_3lyr_ap_fixed_ap_fixed_config10_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dense_mult_3lyr_ap_fixed_ap_fixed_config10_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv16_E0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011100000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_B0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010110000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv16_FFAA : STD_LOGIC_VECTOR (15 downto 0) := "1111111110101010";
    constant ap_const_lv21_1FFFF3 : STD_LOGIC_VECTOR (20 downto 0) := "111111111111111110011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv24_FFFFBA : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110111010";
    constant ap_const_lv22_3FFFE7 : STD_LOGIC_VECTOR (21 downto 0) := "1111111111111111100111";
    constant ap_const_lv24_4F : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001001111";
    constant ap_const_lv24_FFFF4F : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111101001111";
    constant ap_const_lv24_BA : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000010111010";
    constant ap_const_lv24_5D : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001011101";
    constant ap_const_lv24_FFFF9B : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110011011";
    constant ap_const_lv23_7FFFD9 : STD_LOGIC_VECTOR (22 downto 0) := "11111111111111111011001";
    constant ap_const_lv23_7FFFC5 : STD_LOGIC_VECTOR (22 downto 0) := "11111111111111111000101";
    constant ap_const_lv24_FFFFB5 : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110110101";
    constant ap_const_lv24_47 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001000111";
    constant ap_const_lv23_7FFFDB : STD_LOGIC_VECTOR (22 downto 0) := "11111111111111111011011";
    constant ap_const_lv24_FFFFA5 : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110100101";
    constant ap_const_lv23_2D : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000101101";

    signal data0_logits_0_V_reg_1090 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal data0_logits_1_V_reg_1095 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_logits_2_V_reg_1100 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_logits_3_V_reg_1105 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_logits_4_V_reg_1110 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_logits_5_V_reg_1115 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_logits_6_V_reg_1120 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_logits_7_V_reg_1125 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_0_V_reg_1130 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_1_V_reg_1135 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_2_V_reg_1140 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_3_V_reg_1145 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_4_V_reg_1150 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_5_V_reg_1155 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_6_V_reg_1160 : STD_LOGIC_VECTOR (15 downto 0);
    signal data0_7_V_reg_1165 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_logits_0_V_reg_1170 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_logits_1_V_reg_1175 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_logits_2_V_reg_1180 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_logits_3_V_reg_1185 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_logits_4_V_reg_1190 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_logits_5_V_reg_1195 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_logits_6_V_reg_1200 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_logits_7_V_reg_1205 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_0_V_reg_1210 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_1_V_reg_1216 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_2_V_reg_1223 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_3_V_reg_1231 : STD_LOGIC_VECTOR (15 downto 0);
    signal data1_4_V_reg_1237 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_333_fu_479_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_333_reg_1244 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_241_reg_1249 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln708_242_reg_1254 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_338_fu_555_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln703_338_reg_1259 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln708_248_reg_1264 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_348_fu_599_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_348_reg_1269 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call25 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call25 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call25 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call25 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call25 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call25 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call25 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp34 : BOOLEAN;
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call7 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call7 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call7 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call7 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call7 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call7 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call7 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp15 : BOOLEAN;
    signal call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_ready : STD_LOGIC;
    signal call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_ready : STD_LOGIC;
    signal call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sext_ln1118_183_fu_358_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_170_fu_992_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln1118_185_fu_375_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1118_186_fu_379_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1118_65_fu_383_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1118_65_fu_383_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln1118_187_fu_391_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln1118_55_fu_395_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln1118_186_fu_379_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln1118_56_fu_401_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln708_235_fu_407_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1118_189_fu_425_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1118_66_fu_429_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1118_66_fu_429_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln1118_190_fu_437_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln1118_57_fu_441_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln1118_189_fu_425_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln1118_58_fu_447_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln708_236_fu_453_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln708_234_fu_362_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln708_100_fu_417_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln708_101_fu_463_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_332_fu_473_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_331_fu_467_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_174_fu_999_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_fu_485_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_260_fu_498_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_260_fu_498_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln1118_68_fu_512_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1118_68_fu_512_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln1118_192_fu_520_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sub_ln1118_59_fu_524_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln1118_185_fu_375_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sub_ln1118_60_fu_530_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal mul_ln1118_175_fu_1006_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln708_104_fu_494_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln1118_195_fu_508_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln1118_180_fu_1013_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln1118_181_fu_1020_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln708_250_fu_579_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_250_fu_579_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln708_110_fu_589_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_347_fu_593_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_249_fu_570_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_fu_1027_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln1118_168_fu_1034_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln_fu_641_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal shl_ln1118_s_fu_652_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1118_178_fu_659_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln1118_177_fu_648_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln1118_fu_663_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln708_232_fu_669_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln1118_169_fu_1041_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln708_233_fu_692_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln_fu_611_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_s_fu_626_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln708_fu_679_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln708_99_fu_701_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_329_fu_711_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_fu_705_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_330_fu_717_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_171_fu_1048_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln708_237_fu_728_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln1118_67_fu_741_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1118_191_fu_748_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln1118_174_fu_623_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln1118_fu_752_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln708_238_fu_758_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1118_172_fu_1055_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln1118_173_fu_1062_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln708_102_fu_737_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln708_103_fu_768_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_239_fu_772_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_240_fu_781_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_336_fu_799_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_335_fu_793_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_339_fu_814_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln708_105_fu_790_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_340_fu_819_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_fu_811_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_341_fu_825_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_337_fu_805_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_176_fu_1069_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln708_243_fu_837_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln1118_177_fu_1076_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln1118_178_fu_859_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_178_fu_859_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln708_245_fu_865_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln1118_179_fu_1083_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln708_246_fu_879_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln1118_69_fu_892_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln1118_193_fu_899_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal shl_ln1118_70_fu_909_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln1118_61_fu_903_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln1118_194_fu_916_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln1118_62_fu_920_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln708_247_fu_926_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln708_106_fu_846_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_244_fu_850_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln708_107_fu_875_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln708_108_fu_888_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_344_fu_946_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_343_fu_940_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln708_109_fu_936_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_346_fu_958_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_349_fu_963_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_345_fu_952_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_334_fu_723_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_1_V_fu_831_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_2_V_fu_968_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_170_fu_992_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1118_183_fu_358_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln1118_170_fu_992_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_174_fu_999_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln1118_175_fu_1006_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_180_fu_1013_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_180_fu_1013_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln1118_181_fu_1020_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln1118_fu_1027_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_168_fu_1034_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1118_173_fu_620_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln1118_168_fu_1034_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_169_fu_1041_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln1118_171_fu_1048_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1118_172_fu_608_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mul_ln1118_171_fu_1048_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln1118_172_fu_1055_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_173_fu_1062_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_176_fu_1069_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_176_fu_1069_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln1118_177_fu_1076_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_177_fu_1076_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_179_fu_1083_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal data_0_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal data_1_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal data_2_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal data_3_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal data_4_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal data_5_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal data_6_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);

    component dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2 IS
    port (
        ap_ready : OUT STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2 IS
    port (
        ap_ready : OUT STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component myproject_mul_mul_16s_8s_24_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component myproject_mul_mul_16s_6s_22_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component myproject_mul_mul_16s_8ns_24_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component myproject_mul_mul_16s_9s_24_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component myproject_mul_mul_16s_9ns_24_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component myproject_mul_mul_16s_7s_23_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;


    component myproject_mul_mul_16s_7ns_23_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;



begin
    grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172 : component dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_0_V_read => data0_0_V_reg_1130,
        data_1_V_read => data0_1_V_reg_1135,
        data_2_V_read => data0_2_V_reg_1140,
        data_3_V_read => data0_3_V_reg_1145,
        data_4_V_read => data0_4_V_reg_1150,
        data_5_V_read => data0_5_V_reg_1155,
        data_6_V_read => data0_6_V_reg_1160,
        data_7_V_read => data0_7_V_reg_1165,
        ap_return_0 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_0,
        ap_return_1 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_1,
        ap_return_2 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_2,
        ap_return_3 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_3,
        ap_return_4 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_4,
        ap_return_5 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_5,
        ap_return_6 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_6,
        ap_return_7 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_7,
        ap_ce => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_ce);

    grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184 : component dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_0_V_read => data_0_V_read_int_reg,
        data_1_V_read => data_1_V_read_int_reg,
        data_2_V_read => data_2_V_read_int_reg,
        data_3_V_read => data_3_V_read_int_reg,
        data_4_V_read => data_4_V_read_int_reg,
        data_5_V_read => data_5_V_read_int_reg,
        data_6_V_read => data_6_V_read_int_reg,
        ap_return_0 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_0,
        ap_return_1 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_1,
        ap_return_2 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_2,
        ap_return_3 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_3,
        ap_return_4 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_4,
        ap_return_5 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_5,
        ap_return_6 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_6,
        ap_return_7 => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_7,
        ap_ce => grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_ce);

    call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202 : component relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2
    port map (
        ap_ready => call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_ready,
        data_0_V_read => data0_logits_0_V_reg_1090,
        data_1_V_read => data0_logits_1_V_reg_1095,
        data_2_V_read => data0_logits_2_V_reg_1100,
        data_3_V_read => data0_logits_3_V_reg_1105,
        data_4_V_read => data0_logits_4_V_reg_1110,
        data_5_V_read => data0_logits_5_V_reg_1115,
        data_6_V_read => data0_logits_6_V_reg_1120,
        data_7_V_read => data0_logits_7_V_reg_1125,
        ap_return_0 => call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_0,
        ap_return_1 => call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_1,
        ap_return_2 => call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_2,
        ap_return_3 => call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_3,
        ap_return_4 => call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_4,
        ap_return_5 => call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_5,
        ap_return_6 => call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_6,
        ap_return_7 => call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_7);

    call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214 : component relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2
    port map (
        ap_ready => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_ready,
        data_0_V_read => data1_logits_0_V_reg_1170,
        data_1_V_read => data1_logits_1_V_reg_1175,
        data_2_V_read => data1_logits_2_V_reg_1180,
        data_3_V_read => data1_logits_3_V_reg_1185,
        data_4_V_read => data1_logits_4_V_reg_1190,
        data_5_V_read => data1_logits_5_V_reg_1195,
        data_6_V_read => data1_logits_6_V_reg_1200,
        data_7_V_read => data1_logits_7_V_reg_1205,
        ap_return_0 => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_0,
        ap_return_1 => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_1,
        ap_return_2 => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_2,
        ap_return_3 => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_3,
        ap_return_4 => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_4,
        ap_return_5 => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_5,
        ap_return_6 => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_6,
        ap_return_7 => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_7);

    myproject_mul_mul_16s_8s_24_1_0_U1597 : component myproject_mul_mul_16s_8s_24_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln1118_170_fu_992_p0,
        din1 => mul_ln1118_170_fu_992_p1,
        dout => mul_ln1118_170_fu_992_p2);

    myproject_mul_mul_16s_6s_22_1_0_U1598 : component myproject_mul_mul_16s_6s_22_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 6,
        dout_WIDTH => 22)
    port map (
        din0 => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_4,
        din1 => mul_ln1118_174_fu_999_p1,
        dout => mul_ln1118_174_fu_999_p2);

    myproject_mul_mul_16s_8ns_24_1_0_U1599 : component myproject_mul_mul_16s_8ns_24_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_7,
        din1 => mul_ln1118_175_fu_1006_p1,
        dout => mul_ln1118_175_fu_1006_p2);

    myproject_mul_mul_16s_9s_24_1_0_U1600 : component myproject_mul_mul_16s_9s_24_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln1118_180_fu_1013_p0,
        din1 => mul_ln1118_180_fu_1013_p1,
        dout => mul_ln1118_180_fu_1013_p2);

    myproject_mul_mul_16s_9ns_24_1_0_U1601 : component myproject_mul_mul_16s_9ns_24_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 24)
    port map (
        din0 => call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_6,
        din1 => mul_ln1118_181_fu_1020_p1,
        dout => mul_ln1118_181_fu_1020_p2);

    myproject_mul_mul_16s_8ns_24_1_0_U1602 : component myproject_mul_mul_16s_8ns_24_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => data1_0_V_reg_1210,
        din1 => mul_ln1118_fu_1027_p1,
        dout => mul_ln1118_fu_1027_p2);

    myproject_mul_mul_16s_8s_24_1_0_U1603 : component myproject_mul_mul_16s_8s_24_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln1118_168_fu_1034_p0,
        din1 => mul_ln1118_168_fu_1034_p1,
        dout => mul_ln1118_168_fu_1034_p2);

    myproject_mul_mul_16s_7s_23_1_0_U1604 : component myproject_mul_mul_16s_7s_23_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 7,
        dout_WIDTH => 23)
    port map (
        din0 => data1_4_V_reg_1237,
        din1 => mul_ln1118_169_fu_1041_p1,
        dout => mul_ln1118_169_fu_1041_p2);

    myproject_mul_mul_16s_7s_23_1_0_U1605 : component myproject_mul_mul_16s_7s_23_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 7,
        dout_WIDTH => 23)
    port map (
        din0 => mul_ln1118_171_fu_1048_p0,
        din1 => mul_ln1118_171_fu_1048_p1,
        dout => mul_ln1118_171_fu_1048_p2);

    myproject_mul_mul_16s_8s_24_1_0_U1606 : component myproject_mul_mul_16s_8s_24_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => data1_2_V_reg_1223,
        din1 => mul_ln1118_172_fu_1055_p1,
        dout => mul_ln1118_172_fu_1055_p2);

    myproject_mul_mul_16s_8ns_24_1_0_U1607 : component myproject_mul_mul_16s_8ns_24_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => data1_3_V_reg_1231,
        din1 => mul_ln1118_173_fu_1062_p1,
        dout => mul_ln1118_173_fu_1062_p2);

    myproject_mul_mul_16s_7s_23_1_0_U1608 : component myproject_mul_mul_16s_7s_23_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 7,
        dout_WIDTH => 23)
    port map (
        din0 => mul_ln1118_176_fu_1069_p0,
        din1 => mul_ln1118_176_fu_1069_p1,
        dout => mul_ln1118_176_fu_1069_p2);

    myproject_mul_mul_16s_8s_24_1_0_U1609 : component myproject_mul_mul_16s_8s_24_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => mul_ln1118_177_fu_1076_p0,
        din1 => mul_ln1118_177_fu_1076_p1,
        dout => mul_ln1118_177_fu_1076_p2);

    myproject_mul_mul_16s_7ns_23_1_0_U1610 : component myproject_mul_mul_16s_7ns_23_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 7,
        dout_WIDTH => 23)
    port map (
        din0 => data1_3_V_reg_1231,
        din1 => mul_ln1118_179_fu_1083_p1,
        dout => mul_ln1118_179_fu_1083_p2);





    data_0_V_read_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            data_0_V_read_int_reg <= data_0_V_read;
        end if;
    end process;

    data_1_V_read_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            data_1_V_read_int_reg <= data_1_V_read;
        end if;
    end process;

    data_2_V_read_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            data_2_V_read_int_reg <= data_2_V_read;
        end if;
    end process;

    data_3_V_read_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            data_3_V_read_int_reg <= data_3_V_read;
        end if;
    end process;

    data_4_V_read_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            data_4_V_read_int_reg <= data_4_V_read;
        end if;
    end process;

    data_5_V_read_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            data_5_V_read_int_reg <= data_5_V_read;
        end if;
    end process;

    data_6_V_read_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            data_6_V_read_int_reg <= data_6_V_read;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln703_333_reg_1244 <= add_ln703_333_fu_479_p2;
                add_ln703_338_reg_1259 <= add_ln703_338_fu_555_p2;
                add_ln703_348_reg_1269 <= add_ln703_348_fu_599_p2;
                data0_0_V_reg_1130 <= call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_0;
                data0_1_V_reg_1135 <= call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_1;
                data0_2_V_reg_1140 <= call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_2;
                data0_3_V_reg_1145 <= call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_3;
                data0_4_V_reg_1150 <= call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_4;
                data0_5_V_reg_1155 <= call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_5;
                data0_6_V_reg_1160 <= call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_6;
                data0_7_V_reg_1165 <= call_ret49_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_2_fu_202_ap_return_7;
                data0_logits_0_V_reg_1090 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_0;
                data0_logits_1_V_reg_1095 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_1;
                data0_logits_2_V_reg_1100 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_2;
                data0_logits_3_V_reg_1105 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_3;
                data0_logits_4_V_reg_1110 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_4;
                data0_logits_5_V_reg_1115 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_5;
                data0_logits_6_V_reg_1120 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_6;
                data0_logits_7_V_reg_1125 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_return_7;
                data1_0_V_reg_1210 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_0;
                data1_1_V_reg_1216 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_1;
                data1_2_V_reg_1223 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_2;
                data1_3_V_reg_1231 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_3;
                data1_4_V_reg_1237 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_4;
                data1_logits_0_V_reg_1170 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_0;
                data1_logits_1_V_reg_1175 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_1;
                data1_logits_2_V_reg_1180 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_2;
                data1_logits_3_V_reg_1185 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_3;
                data1_logits_4_V_reg_1190 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_4;
                data1_logits_5_V_reg_1195 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_5;
                data1_logits_6_V_reg_1200 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_6;
                data1_logits_7_V_reg_1205 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_return_7;
                trunc_ln708_241_reg_1249 <= sub_ln1118_60_fu_530_p2(19 downto 8);
                trunc_ln708_242_reg_1254 <= mul_ln1118_175_fu_1006_p2(23 downto 8);
                trunc_ln708_248_reg_1264 <= mul_ln1118_180_fu_1013_p2(23 downto 8);
            end if;
        end if;
    end process;
    acc_1_V_fu_831_p2 <= std_logic_vector(unsigned(add_ln703_341_fu_825_p2) + unsigned(add_ln703_337_fu_805_p2));
    acc_2_V_fu_968_p2 <= std_logic_vector(unsigned(add_ln703_349_fu_963_p2) + unsigned(add_ln703_345_fu_952_p2));
    add_ln1118_fu_752_p2 <= std_logic_vector(signed(sext_ln1118_191_fu_748_p1) + signed(sext_ln1118_174_fu_623_p1));
    add_ln703_329_fu_711_p2 <= std_logic_vector(signed(sext_ln708_fu_679_p1) + signed(sext_ln708_99_fu_701_p1));
    add_ln703_330_fu_717_p2 <= std_logic_vector(unsigned(add_ln703_329_fu_711_p2) + unsigned(add_ln703_fu_705_p2));
    add_ln703_331_fu_467_p2 <= std_logic_vector(unsigned(trunc_ln708_234_fu_362_p4) + unsigned(sext_ln708_100_fu_417_p1));
    add_ln703_332_fu_473_p2 <= std_logic_vector(signed(sext_ln708_101_fu_463_p1) + signed(ap_const_lv16_E0));
    add_ln703_333_fu_479_p2 <= std_logic_vector(unsigned(add_ln703_332_fu_473_p2) + unsigned(add_ln703_331_fu_467_p2));
    add_ln703_334_fu_723_p2 <= std_logic_vector(unsigned(add_ln703_333_reg_1244) + unsigned(add_ln703_330_fu_717_p2));
    add_ln703_335_fu_793_p2 <= std_logic_vector(signed(sext_ln708_102_fu_737_p1) + signed(sext_ln708_103_fu_768_p1));
    add_ln703_336_fu_799_p2 <= std_logic_vector(unsigned(trunc_ln708_239_fu_772_p4) + unsigned(trunc_ln708_240_fu_781_p4));
    add_ln703_337_fu_805_p2 <= std_logic_vector(unsigned(add_ln703_336_fu_799_p2) + unsigned(add_ln703_335_fu_793_p2));
    add_ln703_338_fu_555_p2 <= std_logic_vector(signed(sext_ln708_104_fu_494_p1) + signed(sext_ln1118_195_fu_508_p1));
    add_ln703_339_fu_814_p2 <= std_logic_vector(unsigned(trunc_ln708_242_reg_1254) + unsigned(ap_const_lv16_FFAA));
    add_ln703_340_fu_819_p2 <= std_logic_vector(unsigned(add_ln703_339_fu_814_p2) + unsigned(sext_ln708_105_fu_790_p1));
    add_ln703_341_fu_825_p2 <= std_logic_vector(unsigned(add_ln703_340_fu_819_p2) + unsigned(sext_ln703_fu_811_p1));
    add_ln703_343_fu_940_p2 <= std_logic_vector(signed(sext_ln708_106_fu_846_p1) + signed(trunc_ln708_244_fu_850_p4));
    add_ln703_344_fu_946_p2 <= std_logic_vector(signed(sext_ln708_107_fu_875_p1) + signed(sext_ln708_108_fu_888_p1));
    add_ln703_345_fu_952_p2 <= std_logic_vector(unsigned(add_ln703_344_fu_946_p2) + unsigned(add_ln703_343_fu_940_p2));
    add_ln703_346_fu_958_p2 <= std_logic_vector(signed(sext_ln708_109_fu_936_p1) + signed(trunc_ln708_248_reg_1264));
    add_ln703_347_fu_593_p2 <= std_logic_vector(signed(sext_ln708_110_fu_589_p1) + signed(ap_const_lv16_B0));
    add_ln703_348_fu_599_p2 <= std_logic_vector(unsigned(add_ln703_347_fu_593_p2) + unsigned(trunc_ln708_249_fu_570_p4));
    add_ln703_349_fu_963_p2 <= std_logic_vector(unsigned(add_ln703_348_reg_1269) + unsigned(add_ln703_346_fu_958_p2));
    add_ln703_fu_705_p2 <= std_logic_vector(unsigned(trunc_ln_fu_611_p4) + unsigned(trunc_ln708_s_fu_626_p4));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return_0 <= add_ln703_334_fu_723_p2;
    ap_return_1 <= acc_1_V_fu_831_p2;
    ap_return_2 <= acc_2_V_fu_968_p2;

    grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp34)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp34)) then 
            grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_ce <= ap_const_logic_1;
        else 
            grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_4_fu_172_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp15)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp15)) then 
            grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_ce <= ap_const_logic_1;
        else 
            grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_5_fu_184_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln1118_168_fu_1034_p0 <= sext_ln1118_173_fu_620_p1(16 - 1 downto 0);
    mul_ln1118_168_fu_1034_p1 <= ap_const_lv24_FFFF9B(8 - 1 downto 0);
    mul_ln1118_169_fu_1041_p1 <= ap_const_lv23_7FFFD9(7 - 1 downto 0);
    mul_ln1118_170_fu_992_p0 <= sext_ln1118_183_fu_358_p1(16 - 1 downto 0);
    mul_ln1118_170_fu_992_p1 <= ap_const_lv24_FFFFBA(8 - 1 downto 0);
    mul_ln1118_171_fu_1048_p0 <= sext_ln1118_172_fu_608_p1(16 - 1 downto 0);
    mul_ln1118_171_fu_1048_p1 <= ap_const_lv23_7FFFC5(7 - 1 downto 0);
    mul_ln1118_172_fu_1055_p1 <= ap_const_lv24_FFFFB5(8 - 1 downto 0);
    mul_ln1118_173_fu_1062_p1 <= ap_const_lv24_47(8 - 1 downto 0);
    mul_ln1118_174_fu_999_p1 <= ap_const_lv22_3FFFE7(6 - 1 downto 0);
    mul_ln1118_175_fu_1006_p1 <= ap_const_lv24_4F(8 - 1 downto 0);
    mul_ln1118_176_fu_1069_p0 <= sext_ln1118_172_fu_608_p1(16 - 1 downto 0);
    mul_ln1118_176_fu_1069_p1 <= ap_const_lv23_7FFFDB(7 - 1 downto 0);
    mul_ln1118_177_fu_1076_p0 <= sext_ln1118_173_fu_620_p1(16 - 1 downto 0);
    mul_ln1118_177_fu_1076_p1 <= ap_const_lv24_FFFFA5(8 - 1 downto 0);
    mul_ln1118_178_fu_859_p0 <= data1_2_V_reg_1223;
    mul_ln1118_178_fu_859_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_178_fu_859_p0) * signed(ap_const_lv21_1FFFF3))), 21));
    mul_ln1118_179_fu_1083_p1 <= ap_const_lv23_2D(7 - 1 downto 0);
    mul_ln1118_180_fu_1013_p0 <= sext_ln1118_183_fu_358_p1(16 - 1 downto 0);
    mul_ln1118_180_fu_1013_p1 <= ap_const_lv24_FFFF4F(9 - 1 downto 0);
    mul_ln1118_181_fu_1020_p1 <= ap_const_lv24_BA(9 - 1 downto 0);
    mul_ln1118_fu_1027_p1 <= ap_const_lv24_5D(8 - 1 downto 0);
        sext_ln1118_172_fu_608_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data1_0_V_reg_1210),23));

        sext_ln1118_173_fu_620_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data1_1_V_reg_1216),24));

        sext_ln1118_174_fu_623_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data1_1_V_reg_1216),19));

        sext_ln1118_177_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_641_p3),22));

        sext_ln1118_178_fu_659_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_s_fu_652_p3),22));

    sext_ln1118_183_fu_358_p0 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_5;
        sext_ln1118_183_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_183_fu_358_p0),24));

    sext_ln1118_185_fu_375_p0 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_6;
        sext_ln1118_185_fu_375_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_185_fu_375_p0),20));

    sext_ln1118_186_fu_379_p0 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_6;
        sext_ln1118_186_fu_379_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_186_fu_379_p0),22));

        sext_ln1118_187_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_65_fu_383_p3),22));

    sext_ln1118_189_fu_425_p0 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_7;
        sext_ln1118_189_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_189_fu_425_p0),23));

        sext_ln1118_190_fu_437_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_66_fu_429_p3),23));

        sext_ln1118_191_fu_748_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_67_fu_741_p3),19));

        sext_ln1118_192_fu_520_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_68_fu_512_p3),20));

        sext_ln1118_193_fu_899_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_69_fu_892_p3),21));

        sext_ln1118_194_fu_916_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_70_fu_909_p3),21));

        sext_ln1118_195_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_260_fu_498_p4),15));

        sext_ln703_fu_811_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln703_338_reg_1259),16));

        sext_ln708_100_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_235_fu_407_p4),16));

        sext_ln708_101_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_236_fu_453_p4),16));

        sext_ln708_102_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_237_fu_728_p4),16));

        sext_ln708_103_fu_768_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_238_fu_758_p4),16));

        sext_ln708_104_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_485_p4),15));

        sext_ln708_105_fu_790_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_241_reg_1249),16));

        sext_ln708_106_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_243_fu_837_p4),16));

        sext_ln708_107_fu_875_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_245_fu_865_p4),16));

        sext_ln708_108_fu_888_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_246_fu_879_p4),16));

        sext_ln708_109_fu_936_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_247_fu_926_p4),16));

        sext_ln708_110_fu_589_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_250_fu_579_p4),16));

        sext_ln708_99_fu_701_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_233_fu_692_p4),16));

        sext_ln708_fu_679_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_232_fu_669_p4),16));

    shl_ln1118_65_fu_383_p1 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_6;
    shl_ln1118_65_fu_383_p3 <= (shl_ln1118_65_fu_383_p1 & ap_const_lv5_0);
    shl_ln1118_66_fu_429_p1 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_7;
    shl_ln1118_66_fu_429_p3 <= (shl_ln1118_66_fu_429_p1 & ap_const_lv6_0);
    shl_ln1118_67_fu_741_p3 <= (data1_1_V_reg_1216 & ap_const_lv2_0);
    shl_ln1118_68_fu_512_p1 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_6;
    shl_ln1118_68_fu_512_p3 <= (shl_ln1118_68_fu_512_p1 & ap_const_lv3_0);
    shl_ln1118_69_fu_892_p3 <= (data1_4_V_reg_1237 & ap_const_lv4_0);
    shl_ln1118_70_fu_909_p3 <= (data1_4_V_reg_1237 & ap_const_lv2_0);
    shl_ln1118_s_fu_652_p3 <= (data1_2_V_reg_1223 & ap_const_lv1_0);
    shl_ln_fu_641_p3 <= (data1_2_V_reg_1223 & ap_const_lv5_0);
    sub_ln1118_55_fu_395_p2 <= std_logic_vector(unsigned(ap_const_lv22_0) - unsigned(sext_ln1118_187_fu_391_p1));
    sub_ln1118_56_fu_401_p2 <= std_logic_vector(unsigned(sub_ln1118_55_fu_395_p2) - unsigned(sext_ln1118_186_fu_379_p1));
    sub_ln1118_57_fu_441_p2 <= std_logic_vector(unsigned(ap_const_lv23_0) - unsigned(sext_ln1118_190_fu_437_p1));
    sub_ln1118_58_fu_447_p2 <= std_logic_vector(unsigned(sub_ln1118_57_fu_441_p2) - unsigned(sext_ln1118_189_fu_425_p1));
    sub_ln1118_59_fu_524_p2 <= std_logic_vector(unsigned(ap_const_lv20_0) - unsigned(sext_ln1118_192_fu_520_p1));
    sub_ln1118_60_fu_530_p2 <= std_logic_vector(unsigned(sub_ln1118_59_fu_524_p2) - unsigned(sext_ln1118_185_fu_375_p1));
    sub_ln1118_61_fu_903_p2 <= std_logic_vector(unsigned(ap_const_lv21_0) - unsigned(sext_ln1118_193_fu_899_p1));
    sub_ln1118_62_fu_920_p2 <= std_logic_vector(unsigned(sub_ln1118_61_fu_903_p2) - unsigned(sext_ln1118_194_fu_916_p1));
    sub_ln1118_fu_663_p2 <= std_logic_vector(signed(sext_ln1118_178_fu_659_p1) - signed(sext_ln1118_177_fu_648_p1));
    tmp_260_fu_498_p1 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_5;
    tmp_260_fu_498_p4 <= tmp_260_fu_498_p1(15 downto 7);
    tmp_fu_485_p4 <= mul_ln1118_174_fu_999_p2(21 downto 8);
    trunc_ln708_232_fu_669_p4 <= sub_ln1118_fu_663_p2(21 downto 8);
    trunc_ln708_233_fu_692_p4 <= mul_ln1118_169_fu_1041_p2(22 downto 8);
    trunc_ln708_234_fu_362_p4 <= mul_ln1118_170_fu_992_p2(23 downto 8);
    trunc_ln708_235_fu_407_p4 <= sub_ln1118_56_fu_401_p2(21 downto 8);
    trunc_ln708_236_fu_453_p4 <= sub_ln1118_58_fu_447_p2(22 downto 8);
    trunc_ln708_237_fu_728_p4 <= mul_ln1118_171_fu_1048_p2(22 downto 8);
    trunc_ln708_238_fu_758_p4 <= add_ln1118_fu_752_p2(18 downto 8);
    trunc_ln708_239_fu_772_p4 <= mul_ln1118_172_fu_1055_p2(23 downto 8);
    trunc_ln708_240_fu_781_p4 <= mul_ln1118_173_fu_1062_p2(23 downto 8);
    trunc_ln708_243_fu_837_p4 <= mul_ln1118_176_fu_1069_p2(22 downto 8);
    trunc_ln708_244_fu_850_p4 <= mul_ln1118_177_fu_1076_p2(23 downto 8);
    trunc_ln708_245_fu_865_p4 <= mul_ln1118_178_fu_859_p2(20 downto 8);
    trunc_ln708_246_fu_879_p4 <= mul_ln1118_179_fu_1083_p2(22 downto 8);
    trunc_ln708_247_fu_926_p4 <= sub_ln1118_62_fu_920_p2(20 downto 8);
    trunc_ln708_249_fu_570_p4 <= mul_ln1118_181_fu_1020_p2(23 downto 8);
    trunc_ln708_250_fu_579_p1 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_2_fu_214_ap_return_7;
    trunc_ln708_250_fu_579_p4 <= trunc_ln708_250_fu_579_p1(15 downto 1);
    trunc_ln708_s_fu_626_p4 <= mul_ln1118_168_fu_1034_p2(23 downto 8);
    trunc_ln_fu_611_p4 <= mul_ln1118_fu_1027_p2(23 downto 8);
end behav;
