-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reduce_ap_fixed_16_Op_add_ap_fixed_16_8_5_3_0_s is
port (
    ap_ready : OUT STD_LOGIC;
    x_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_10_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_11_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_12_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_13_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_14_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    x_15_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of reduce_ap_fixed_16_Op_add_ap_fixed_16_8_5_3_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal add_ln703_2_fu_136_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_1_fu_130_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_5_fu_154_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_4_fu_148_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_6_fu_160_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_3_fu_142_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_9_fu_178_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_8_fu_172_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_12_fu_196_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_11_fu_190_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_13_fu_202_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_10_fu_184_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_14_fu_208_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_7_fu_166_p2 : STD_LOGIC_VECTOR (15 downto 0);


begin



    add_ln703_10_fu_184_p2 <= std_logic_vector(unsigned(add_ln703_9_fu_178_p2) + unsigned(add_ln703_8_fu_172_p2));
    add_ln703_11_fu_190_p2 <= std_logic_vector(unsigned(x_4_V_read) + unsigned(x_5_V_read));
    add_ln703_12_fu_196_p2 <= std_logic_vector(unsigned(x_6_V_read) + unsigned(x_7_V_read));
    add_ln703_13_fu_202_p2 <= std_logic_vector(unsigned(add_ln703_12_fu_196_p2) + unsigned(add_ln703_11_fu_190_p2));
    add_ln703_14_fu_208_p2 <= std_logic_vector(unsigned(add_ln703_13_fu_202_p2) + unsigned(add_ln703_10_fu_184_p2));
    add_ln703_1_fu_130_p2 <= std_logic_vector(unsigned(x_15_V_read) + unsigned(x_14_V_read));
    add_ln703_2_fu_136_p2 <= std_logic_vector(unsigned(x_12_V_read) + unsigned(x_13_V_read));
    add_ln703_3_fu_142_p2 <= std_logic_vector(unsigned(add_ln703_2_fu_136_p2) + unsigned(add_ln703_1_fu_130_p2));
    add_ln703_4_fu_148_p2 <= std_logic_vector(unsigned(x_8_V_read) + unsigned(x_9_V_read));
    add_ln703_5_fu_154_p2 <= std_logic_vector(unsigned(x_10_V_read) + unsigned(x_11_V_read));
    add_ln703_6_fu_160_p2 <= std_logic_vector(unsigned(add_ln703_5_fu_154_p2) + unsigned(add_ln703_4_fu_148_p2));
    add_ln703_7_fu_166_p2 <= std_logic_vector(unsigned(add_ln703_6_fu_160_p2) + unsigned(add_ln703_3_fu_142_p2));
    add_ln703_8_fu_172_p2 <= std_logic_vector(unsigned(x_0_V_read) + unsigned(x_1_V_read));
    add_ln703_9_fu_178_p2 <= std_logic_vector(unsigned(x_2_V_read) + unsigned(x_3_V_read));
    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(unsigned(add_ln703_14_fu_208_p2) + unsigned(add_ln703_7_fu_166_p2));
end behav;
