// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3 (
        ap_clk,
        ap_rst,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_V_read;
input  [15:0] data_1_V_read;
input  [15:0] data_2_V_read;
input  [15:0] data_3_V_read;
input  [15:0] data_4_V_read;
input  [15:0] data_5_V_read;
input  [15:0] data_6_V_read;
input  [15:0] data_7_V_read;
input  [15:0] data_8_V_read;
input  [15:0] data_9_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;

wire   [15:0] add_ln703_183_fu_515_p2;
reg   [15:0] add_ln703_183_reg_2544;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] add_ln703_185_fu_527_p2;
reg   [15:0] add_ln703_185_reg_2549;
wire   [15:0] add_ln703_187_fu_539_p2;
reg   [15:0] add_ln703_187_reg_2554;
wire   [15:0] add_ln703_193_fu_688_p2;
reg   [15:0] add_ln703_193_reg_2559;
wire   [15:0] add_ln703_195_fu_700_p2;
reg   [15:0] add_ln703_195_reg_2564;
wire   [15:0] add_ln703_197_fu_712_p2;
reg   [15:0] add_ln703_197_reg_2569;
wire   [15:0] add_ln703_203_fu_866_p2;
reg   [15:0] add_ln703_203_reg_2574;
wire   [15:0] add_ln703_205_fu_878_p2;
reg   [15:0] add_ln703_205_reg_2579;
wire   [15:0] add_ln703_207_fu_890_p2;
reg   [15:0] add_ln703_207_reg_2584;
wire   [15:0] add_ln703_213_fu_1105_p2;
reg   [15:0] add_ln703_213_reg_2589;
wire   [15:0] add_ln703_215_fu_1117_p2;
reg   [15:0] add_ln703_215_reg_2594;
wire   [15:0] add_ln703_217_fu_1129_p2;
reg   [15:0] add_ln703_217_reg_2599;
wire   [15:0] add_ln703_223_fu_1380_p2;
reg   [15:0] add_ln703_223_reg_2604;
wire   [15:0] add_ln703_225_fu_1392_p2;
reg   [15:0] add_ln703_225_reg_2609;
wire   [15:0] add_ln703_227_fu_1404_p2;
reg   [15:0] add_ln703_227_reg_2614;
wire   [15:0] add_ln703_233_fu_1562_p2;
reg   [15:0] add_ln703_233_reg_2619;
wire   [15:0] add_ln703_235_fu_1574_p2;
reg   [15:0] add_ln703_235_reg_2624;
wire   [15:0] add_ln703_237_fu_1590_p2;
reg   [15:0] add_ln703_237_reg_2629;
wire   [15:0] add_ln703_243_fu_1712_p2;
reg   [15:0] add_ln703_243_reg_2634;
wire   [15:0] add_ln703_245_fu_1724_p2;
reg   [15:0] add_ln703_245_reg_2639;
wire   [15:0] add_ln703_247_fu_1736_p2;
reg   [15:0] add_ln703_247_reg_2644;
wire   [15:0] add_ln703_253_fu_1963_p2;
reg   [15:0] add_ln703_253_reg_2649;
wire   [15:0] add_ln703_255_fu_1975_p2;
reg   [15:0] add_ln703_255_reg_2654;
wire   [15:0] add_ln703_257_fu_1991_p2;
reg   [15:0] add_ln703_257_reg_2659;
wire  signed [15:0] sext_ln1118_fu_296_p0;
wire    ap_block_pp0_stage0;
wire  signed [22:0] mul_ln1118_fu_2117_p2;
wire   [14:0] trunc_ln_fu_304_p4;
wire  signed [15:0] sext_ln1118_83_fu_317_p0;
wire  signed [15:0] sext_ln1118_85_fu_325_p0;
wire  signed [23:0] mul_ln1118_81_fu_2124_p2;
wire  signed [15:0] sext_ln1118_86_fu_338_p0;
wire  signed [23:0] mul_ln1118_82_fu_2131_p2;
wire  signed [15:0] sext_ln1118_88_fu_355_p0;
wire  signed [15:0] sext_ln1118_90_fu_363_p0;
wire  signed [23:0] mul_ln1118_83_fu_2138_p2;
wire  signed [15:0] sext_ln1118_91_fu_376_p0;
wire  signed [15:0] sext_ln1118_92_fu_380_p0;
wire  signed [15:0] sext_ln1118_93_fu_384_p0;
wire  signed [15:0] tmp_fu_388_p1;
wire   [19:0] tmp_fu_388_p3;
wire  signed [20:0] sext_ln1118_93_fu_384_p1;
wire  signed [20:0] sext_ln1118_94_fu_396_p1;
wire   [20:0] sub_ln1118_27_fu_400_p2;
wire   [12:0] trunc_ln708_101_fu_406_p4;
wire  signed [15:0] sext_ln1118_95_fu_420_p0;
wire  signed [15:0] sext_ln1118_96_fu_424_p0;
wire  signed [23:0] mul_ln1118_84_fu_2145_p2;
wire  signed [23:0] mul_ln1118_85_fu_2152_p2;
wire  signed [23:0] mul_ln1118_86_fu_2159_p2;
wire  signed [15:0] sext_ln1118_99_fu_463_p0;
wire  signed [23:0] mul_ln1118_87_fu_2166_p2;
wire  signed [15:0] sext_ln1118_101_fu_480_p0;
wire  signed [23:0] mul_ln1118_88_fu_2173_p2;
wire   [15:0] trunc_ln708_s_fu_329_p4;
wire  signed [15:0] sext_ln708_fu_313_p1;
wire  signed [15:0] sext_ln708_54_fu_416_p1;
wire   [15:0] trunc_ln708_100_fu_367_p4;
wire   [15:0] trunc_ln708_99_fu_346_p4;
wire   [15:0] add_ln703_181_fu_503_p2;
wire   [15:0] add_ln703_fu_497_p2;
wire   [15:0] add_ln703_182_fu_509_p2;
wire   [15:0] trunc_ln708_104_fu_454_p4;
wire   [15:0] trunc_ln708_103_fu_441_p4;
wire   [15:0] trunc_ln708_102_fu_428_p4;
wire   [15:0] add_ln703_184_fu_521_p2;
wire   [15:0] trunc_ln708_106_fu_488_p4;
wire   [15:0] trunc_ln708_105_fu_471_p4;
wire   [15:0] add_ln703_186_fu_533_p2;
wire  signed [23:0] mul_ln1118_89_fu_2180_p2;
wire  signed [23:0] mul_ln1118_90_fu_2187_p2;
wire  signed [23:0] mul_ln1118_91_fu_2194_p2;
wire  signed [22:0] mul_ln1118_92_fu_2201_p2;
wire   [14:0] trunc_ln708_110_fu_572_p4;
wire  signed [22:0] mul_ln1118_93_fu_2208_p2;
wire   [14:0] trunc_ln708_111_fu_585_p4;
wire  signed [23:0] mul_ln1118_94_fu_2215_p2;
wire  signed [23:0] mul_ln1118_95_fu_2222_p2;
wire  signed [23:0] mul_ln1118_96_fu_2229_p2;
wire  signed [23:0] mul_ln1118_97_fu_2236_p2;
wire  signed [15:0] shl_ln_fu_634_p1;
wire  signed [15:0] shl_ln1118_s_fu_642_p1;
wire   [16:0] shl_ln1118_s_fu_642_p3;
wire   [23:0] shl_ln_fu_634_p3;
wire  signed [23:0] sext_ln1118_103_fu_650_p1;
wire   [23:0] add_ln1118_fu_654_p2;
wire   [15:0] trunc_ln708_108_fu_554_p4;
wire   [15:0] trunc_ln708_107_fu_545_p4;
wire  signed [15:0] sext_ln708_56_fu_594_p1;
wire  signed [15:0] sext_ln708_55_fu_581_p1;
wire   [15:0] trunc_ln708_109_fu_563_p4;
wire   [15:0] add_ln703_191_fu_676_p2;
wire   [15:0] add_ln703_190_fu_670_p2;
wire   [15:0] add_ln703_192_fu_682_p2;
wire   [15:0] trunc_ln708_114_fu_616_p4;
wire   [15:0] trunc_ln708_113_fu_607_p4;
wire   [15:0] trunc_ln708_112_fu_598_p4;
wire   [15:0] add_ln703_194_fu_694_p2;
wire   [15:0] trunc_ln708_116_fu_660_p4;
wire   [15:0] trunc_ln708_115_fu_625_p4;
wire   [15:0] add_ln703_196_fu_706_p2;
wire  signed [23:0] mul_ln1118_98_fu_2243_p2;
wire  signed [23:0] mul_ln1118_99_fu_2250_p2;
wire  signed [15:0] trunc_ln708_119_fu_736_p1;
wire   [14:0] trunc_ln708_119_fu_736_p4;
wire  signed [23:0] mul_ln1118_100_fu_2257_p2;
wire  signed [15:0] shl_ln1118_33_fu_759_p1;
wire   [20:0] shl_ln1118_33_fu_759_p3;
wire  signed [15:0] shl_ln1118_34_fu_771_p1;
wire   [17:0] shl_ln1118_34_fu_771_p3;
wire  signed [21:0] sext_ln1118_104_fu_767_p1;
wire  signed [21:0] sext_ln1118_105_fu_779_p1;
wire   [21:0] add_ln1118_4_fu_783_p2;
wire   [13:0] trunc_ln708_121_fu_789_p4;
wire  signed [23:0] mul_ln1118_101_fu_2264_p2;
wire  signed [23:0] mul_ln1118_102_fu_2271_p2;
wire  signed [23:0] mul_ln1118_103_fu_2278_p2;
wire  signed [23:0] mul_ln1118_104_fu_2285_p2;
wire  signed [23:0] mul_ln1118_105_fu_2292_p2;
wire   [15:0] trunc_ln708_118_fu_727_p4;
wire   [15:0] trunc_ln708_117_fu_718_p4;
wire  signed [15:0] sext_ln708_58_fu_799_p1;
wire   [15:0] trunc_ln708_120_fu_750_p4;
wire  signed [15:0] sext_ln708_57_fu_746_p1;
wire   [15:0] add_ln703_201_fu_854_p2;
wire   [15:0] add_ln703_200_fu_848_p2;
wire   [15:0] add_ln703_202_fu_860_p2;
wire   [15:0] trunc_ln708_124_fu_821_p4;
wire   [15:0] trunc_ln708_123_fu_812_p4;
wire   [15:0] trunc_ln708_122_fu_803_p4;
wire   [15:0] add_ln703_204_fu_872_p2;
wire   [15:0] trunc_ln708_126_fu_839_p4;
wire   [15:0] trunc_ln708_125_fu_830_p4;
wire   [15:0] add_ln703_206_fu_884_p2;
wire  signed [23:0] mul_ln1118_106_fu_2299_p2;
wire  signed [15:0] shl_ln1118_35_fu_905_p1;
wire   [20:0] shl_ln1118_35_fu_905_p3;
wire  signed [15:0] shl_ln1118_36_fu_917_p1;
wire   [17:0] shl_ln1118_36_fu_917_p3;
wire  signed [21:0] sext_ln1118_106_fu_913_p1;
wire  signed [21:0] sext_ln1118_107_fu_925_p1;
wire   [21:0] sub_ln1118_fu_929_p2;
wire   [13:0] trunc_ln708_128_fu_935_p4;
wire  signed [23:0] mul_ln1118_107_fu_2306_p2;
wire  signed [23:0] mul_ln1118_108_fu_2313_p2;
wire  signed [23:0] mul_ln1118_109_fu_2320_p2;
wire  signed [15:0] shl_ln1118_37_fu_976_p1;
wire  signed [15:0] shl_ln1118_38_fu_984_p1;
wire  signed [21:0] shl_ln1118_38_fu_984_p3;
wire   [23:0] shl_ln1118_37_fu_976_p3;
wire  signed [23:0] sext_ln1118_108_fu_992_p1;
wire   [23:0] sub_ln1118_28_fu_996_p2;
wire  signed [23:0] mul_ln1118_110_fu_2327_p2;
wire  signed [23:0] mul_ln1118_111_fu_2334_p2;
wire  signed [15:0] shl_ln1118_39_fu_1030_p1;
wire   [21:0] shl_ln1118_39_fu_1030_p3;
wire  signed [15:0] shl_ln1118_40_fu_1042_p1;
wire  signed [18:0] shl_ln1118_40_fu_1042_p3;
wire  signed [22:0] sext_ln1118_109_fu_1038_p1;
wire  signed [22:0] sext_ln1118_111_fu_1054_p1;
wire   [22:0] add_ln1118_5_fu_1058_p2;
wire   [14:0] trunc_ln708_135_fu_1064_p4;
wire  signed [23:0] mul_ln1118_112_fu_2341_p2;
wire  signed [15:0] sext_ln708_59_fu_945_p1;
wire   [15:0] trunc_ln708_127_fu_896_p4;
wire   [15:0] trunc_ln708_131_fu_967_p4;
wire   [15:0] trunc_ln708_130_fu_958_p4;
wire   [15:0] trunc_ln708_129_fu_949_p4;
wire   [15:0] add_ln703_211_fu_1093_p2;
wire   [15:0] add_ln703_210_fu_1087_p2;
wire   [15:0] add_ln703_212_fu_1099_p2;
wire   [15:0] trunc_ln708_134_fu_1021_p4;
wire   [15:0] trunc_ln708_133_fu_1012_p4;
wire   [15:0] trunc_ln708_132_fu_1002_p4;
wire   [15:0] add_ln703_214_fu_1111_p2;
wire   [15:0] trunc_ln708_136_fu_1078_p4;
wire  signed [15:0] sext_ln708_60_fu_1074_p1;
wire   [15:0] add_ln703_216_fu_1123_p2;
wire  signed [23:0] mul_ln1118_113_fu_2348_p2;
wire  signed [22:0] mul_ln1118_114_fu_2355_p2;
wire   [14:0] trunc_ln708_138_fu_1144_p4;
wire  signed [23:0] mul_ln1118_115_fu_2362_p2;
wire  signed [15:0] mul_ln1118_116_fu_1166_p0;
wire   [20:0] mul_ln1118_116_fu_1166_p2;
wire   [12:0] tmp_241_fu_1172_p4;
wire  signed [15:0] shl_ln1118_41_fu_1186_p1;
wire  signed [16:0] shl_ln1118_41_fu_1186_p3;
wire  signed [20:0] sext_ln1118_114_fu_1198_p1;
wire   [20:0] sub_ln1118_29_fu_1202_p2;
wire   [12:0] tmp_242_fu_1208_p4;
wire  signed [22:0] sext_ln1118_96_fu_424_p1;
wire  signed [22:0] sext_ln1118_115_fu_1222_p1;
wire   [22:0] sub_ln1118_30_fu_1226_p2;
wire   [14:0] trunc_ln708_140_fu_1232_p4;
wire  signed [23:0] mul_ln1118_117_fu_2369_p2;
wire  signed [23:0] mul_ln1118_118_fu_2376_p2;
wire  signed [15:0] shl_ln1118_42_fu_1264_p1;
wire   [20:0] shl_ln1118_42_fu_1264_p3;
wire  signed [21:0] sext_ln1118_116_fu_1272_p1;
wire  signed [15:0] shl_ln1118_43_fu_1282_p1;
wire   [17:0] shl_ln1118_43_fu_1282_p3;
wire   [21:0] sub_ln1118_31_fu_1276_p2;
wire  signed [21:0] sext_ln1118_117_fu_1290_p1;
wire   [21:0] sub_ln1118_32_fu_1294_p2;
wire   [13:0] trunc_ln708_143_fu_1300_p4;
wire  signed [15:0] shl_ln1118_44_fu_1314_p1;
wire   [21:0] shl_ln1118_44_fu_1314_p3;
wire  signed [15:0] shl_ln1118_45_fu_1326_p1;
wire   [18:0] shl_ln1118_45_fu_1326_p3;
wire  signed [22:0] sext_ln1118_118_fu_1322_p1;
wire  signed [22:0] sext_ln1118_119_fu_1334_p1;
wire   [22:0] add_ln1118_6_fu_1338_p2;
wire   [14:0] trunc_ln708_144_fu_1344_p4;
wire  signed [15:0] sext_ln708_61_fu_1153_p1;
wire   [15:0] trunc_ln708_137_fu_1135_p4;
wire  signed [13:0] sext_ln1118_127_fu_1218_p1;
wire  signed [13:0] sext_ln1118_112_fu_1182_p1;
wire   [13:0] add_ln703_221_fu_1364_p2;
wire   [15:0] trunc_ln708_139_fu_1157_p4;
wire  signed [15:0] sext_ln703_fu_1370_p1;
wire   [15:0] add_ln703_220_fu_1358_p2;
wire   [15:0] add_ln703_222_fu_1374_p2;
wire   [15:0] trunc_ln708_142_fu_1255_p4;
wire   [15:0] trunc_ln708_141_fu_1246_p4;
wire  signed [15:0] sext_ln708_62_fu_1242_p1;
wire   [15:0] add_ln703_224_fu_1386_p2;
wire  signed [15:0] sext_ln708_64_fu_1354_p1;
wire  signed [15:0] sext_ln708_63_fu_1310_p1;
wire   [15:0] add_ln703_226_fu_1398_p2;
wire  signed [15:0] trunc_ln708_145_fu_1410_p1;
wire   [7:0] trunc_ln708_145_fu_1410_p4;
wire  signed [21:0] mul_ln1118_119_fu_2383_p2;
wire   [13:0] trunc_ln708_146_fu_1424_p4;
wire  signed [22:0] mul_ln1118_120_fu_2390_p2;
wire   [14:0] trunc_ln708_147_fu_1437_p4;
wire  signed [15:0] shl_ln1118_46_fu_1450_p1;
wire   [17:0] shl_ln1118_46_fu_1450_p3;
wire  signed [18:0] sext_ln1118_121_fu_1458_p1;
wire   [18:0] sub_ln1118_33_fu_1462_p2;
wire   [10:0] trunc_ln708_148_fu_1468_p4;
wire  signed [22:0] mul_ln1118_121_fu_2397_p2;
wire   [14:0] trunc_ln708_149_fu_1482_p4;
wire  signed [22:0] mul_ln1118_122_fu_2404_p2;
wire   [14:0] trunc_ln708_150_fu_1495_p4;
wire  signed [23:0] mul_ln1118_123_fu_2411_p2;
wire  signed [23:0] mul_ln1118_124_fu_2418_p2;
wire  signed [23:0] mul_ln1118_125_fu_2425_p2;
wire  signed [23:0] mul_ln1118_126_fu_2432_p2;
wire  signed [15:0] sext_ln708_66_fu_1446_p1;
wire  signed [15:0] sext_ln708_65_fu_1433_p1;
wire  signed [15:0] sext_ln708_69_fu_1504_p1;
wire  signed [15:0] sext_ln708_68_fu_1491_p1;
wire  signed [15:0] sext_ln708_67_fu_1478_p1;
wire   [15:0] add_ln703_231_fu_1550_p2;
wire   [15:0] add_ln703_230_fu_1544_p2;
wire   [15:0] add_ln703_232_fu_1556_p2;
wire   [15:0] trunc_ln708_153_fu_1526_p4;
wire   [15:0] trunc_ln708_152_fu_1517_p4;
wire   [15:0] trunc_ln708_151_fu_1508_p4;
wire   [15:0] add_ln703_234_fu_1568_p2;
wire  signed [8:0] sext_ln1118_120_fu_1420_p1;
wire   [8:0] add_ln703_236_fu_1580_p2;
wire   [15:0] trunc_ln708_154_fu_1535_p4;
wire   [15:0] zext_ln703_fu_1586_p1;
wire  signed [23:0] mul_ln1118_127_fu_2439_p2;
wire  signed [23:0] mul_ln1118_128_fu_2446_p2;
wire  signed [23:0] mul_ln1118_129_fu_2453_p2;
wire  signed [23:0] mul_ln1118_130_fu_2460_p2;
wire  signed [23:0] mul_ln1118_131_fu_2467_p2;
wire  signed [23:0] mul_ln1118_132_fu_2474_p2;
wire  signed [23:0] mul_ln1118_133_fu_2481_p2;
wire  signed [23:0] mul_ln1118_134_fu_2488_p2;
wire  signed [22:0] mul_ln1118_135_fu_2495_p2;
wire   [14:0] trunc_ln708_163_fu_1668_p4;
wire  signed [22:0] mul_ln1118_136_fu_2502_p2;
wire   [14:0] trunc_ln708_164_fu_1681_p4;
wire   [15:0] trunc_ln708_156_fu_1605_p4;
wire   [15:0] trunc_ln708_155_fu_1596_p4;
wire   [15:0] trunc_ln708_159_fu_1632_p4;
wire   [15:0] trunc_ln708_158_fu_1623_p4;
wire   [15:0] trunc_ln708_157_fu_1614_p4;
wire   [15:0] add_ln703_241_fu_1700_p2;
wire   [15:0] add_ln703_240_fu_1694_p2;
wire   [15:0] add_ln703_242_fu_1706_p2;
wire   [15:0] trunc_ln708_162_fu_1659_p4;
wire   [15:0] trunc_ln708_161_fu_1650_p4;
wire   [15:0] trunc_ln708_160_fu_1641_p4;
wire   [15:0] add_ln703_244_fu_1718_p2;
wire  signed [15:0] sext_ln708_71_fu_1690_p1;
wire  signed [15:0] sext_ln708_70_fu_1677_p1;
wire   [15:0] add_ln703_246_fu_1730_p2;
wire  signed [23:0] mul_ln1118_137_fu_2509_p2;
wire  signed [22:0] mul_ln1118_138_fu_2516_p2;
wire   [14:0] trunc_ln708_166_fu_1751_p4;
wire  signed [15:0] shl_ln1118_47_fu_1764_p1;
wire   [22:0] shl_ln1118_47_fu_1764_p3;
wire  signed [15:0] shl_ln1118_48_fu_1776_p1;
wire   [20:0] shl_ln1118_48_fu_1776_p3;
wire  signed [23:0] sext_ln1118_122_fu_1772_p1;
wire  signed [23:0] sext_ln1118_123_fu_1784_p1;
wire   [23:0] sub_ln1118_34_fu_1788_p2;
wire  signed [15:0] shl_ln1118_49_fu_1804_p1;
wire   [20:0] shl_ln1118_49_fu_1804_p3;
wire  signed [15:0] shl_ln1118_50_fu_1816_p1;
wire   [16:0] shl_ln1118_50_fu_1816_p3;
wire  signed [21:0] sext_ln1118_124_fu_1812_p1;
wire  signed [21:0] sext_ln1118_125_fu_1824_p1;
wire   [21:0] sub_ln1118_35_fu_1828_p2;
wire   [13:0] tmp_243_fu_1834_p4;
wire  signed [15:0] shl_ln1118_51_fu_1848_p1;
wire   [18:0] shl_ln1118_51_fu_1848_p3;
wire  signed [19:0] sext_ln1118_113_fu_1194_p1;
wire  signed [19:0] sext_ln1118_126_fu_1856_p1;
wire   [19:0] sub_ln1118_36_fu_1860_p2;
wire   [11:0] tmp_244_fu_1866_p4;
wire  signed [23:0] mul_ln1118_139_fu_2523_p2;
wire  signed [23:0] mul_ln1118_140_fu_2530_p2;
wire  signed [23:0] mul_ln1118_141_fu_2537_p2;
wire  signed [21:0] sext_ln1118_110_fu_1050_p1;
wire   [21:0] add_ln1118_7_fu_1907_p2;
wire   [13:0] trunc_ln708_171_fu_1913_p4;
wire  signed [15:0] tmp_245_fu_1927_p1;
wire   [13:0] tmp_245_fu_1927_p4;
wire  signed [15:0] sext_ln708_72_fu_1760_p1;
wire   [15:0] trunc_ln708_165_fu_1742_p4;
wire  signed [14:0] sext_ln1118_129_fu_1876_p1;
wire  signed [14:0] sext_ln1118_128_fu_1844_p1;
wire   [14:0] add_ln703_251_fu_1947_p2;
wire   [15:0] trunc_ln708_167_fu_1794_p4;
wire  signed [15:0] sext_ln703_12_fu_1953_p1;
wire   [15:0] add_ln703_250_fu_1941_p2;
wire   [15:0] add_ln703_252_fu_1957_p2;
wire   [15:0] trunc_ln708_170_fu_1898_p4;
wire   [15:0] trunc_ln708_169_fu_1889_p4;
wire   [15:0] trunc_ln708_168_fu_1880_p4;
wire   [15:0] add_ln703_254_fu_1969_p2;
wire  signed [14:0] sext_ln703_11_fu_1937_p1;
wire   [14:0] add_ln703_256_fu_1981_p2;
wire  signed [15:0] sext_ln708_73_fu_1923_p1;
wire  signed [15:0] sext_ln703_13_fu_1987_p1;
wire   [15:0] add_ln703_188_fu_1997_p2;
wire   [15:0] add_ln703_198_fu_2006_p2;
wire   [15:0] add_ln703_208_fu_2015_p2;
wire   [15:0] add_ln703_218_fu_2024_p2;
wire   [15:0] add_ln703_228_fu_2033_p2;
wire   [15:0] add_ln703_238_fu_2042_p2;
wire   [15:0] add_ln703_248_fu_2051_p2;
wire   [15:0] add_ln703_258_fu_2060_p2;
wire   [15:0] add_ln703_189_fu_2001_p2;
wire   [15:0] acc_1_V_fu_2010_p2;
wire   [15:0] acc_2_V_fu_2019_p2;
wire   [15:0] acc_3_V_fu_2028_p2;
wire   [15:0] acc_4_V_fu_2037_p2;
wire   [15:0] acc_5_V_fu_2046_p2;
wire   [15:0] acc_6_V_fu_2055_p2;
wire   [15:0] acc_7_V_fu_2064_p2;
wire   [6:0] mul_ln1118_fu_2117_p1;
wire  signed [15:0] mul_ln1118_81_fu_2124_p0;
wire  signed [23:0] sext_ln1118_83_fu_317_p1;
wire  signed [7:0] mul_ln1118_81_fu_2124_p1;
wire  signed [15:0] mul_ln1118_82_fu_2131_p0;
wire  signed [23:0] sext_ln1118_86_fu_338_p1;
wire  signed [7:0] mul_ln1118_82_fu_2131_p1;
wire  signed [15:0] mul_ln1118_83_fu_2138_p0;
wire  signed [23:0] sext_ln1118_88_fu_355_p1;
wire   [7:0] mul_ln1118_83_fu_2138_p1;
wire  signed [15:0] mul_ln1118_84_fu_2145_p0;
wire  signed [23:0] sext_ln1118_95_fu_420_p1;
wire   [8:0] mul_ln1118_84_fu_2145_p1;
wire  signed [15:0] mul_ln1118_85_fu_2152_p0;
wire  signed [23:0] sext_ln1118_97_fu_437_p1;
wire   [8:0] mul_ln1118_85_fu_2152_p1;
wire  signed [15:0] mul_ln1118_86_fu_2159_p0;
wire  signed [23:0] sext_ln1118_98_fu_450_p1;
wire  signed [9:0] mul_ln1118_86_fu_2159_p1;
wire  signed [15:0] mul_ln1118_87_fu_2166_p0;
wire  signed [23:0] sext_ln1118_99_fu_463_p1;
wire   [7:0] mul_ln1118_87_fu_2166_p1;
wire  signed [15:0] mul_ln1118_88_fu_2173_p0;
wire  signed [23:0] sext_ln1118_101_fu_480_p1;
wire  signed [8:0] mul_ln1118_88_fu_2173_p1;
wire  signed [15:0] mul_ln1118_89_fu_2180_p0;
wire  signed [23:0] sext_ln1118_fu_296_p1;
wire   [8:0] mul_ln1118_89_fu_2180_p1;
wire  signed [15:0] mul_ln1118_90_fu_2187_p0;
wire  signed [7:0] mul_ln1118_90_fu_2187_p1;
wire  signed [15:0] mul_ln1118_91_fu_2194_p0;
wire   [9:0] mul_ln1118_91_fu_2194_p1;
wire  signed [6:0] mul_ln1118_92_fu_2201_p1;
wire  signed [15:0] mul_ln1118_93_fu_2208_p0;
wire  signed [22:0] sext_ln1118_92_fu_380_p1;
wire   [6:0] mul_ln1118_93_fu_2208_p1;
wire  signed [15:0] mul_ln1118_94_fu_2215_p0;
wire  signed [8:0] mul_ln1118_94_fu_2215_p1;
wire  signed [15:0] mul_ln1118_95_fu_2222_p0;
wire  signed [7:0] mul_ln1118_95_fu_2222_p1;
wire  signed [15:0] mul_ln1118_96_fu_2229_p0;
wire   [8:0] mul_ln1118_96_fu_2229_p1;
wire  signed [15:0] mul_ln1118_97_fu_2236_p0;
wire  signed [7:0] mul_ln1118_97_fu_2236_p1;
wire  signed [15:0] mul_ln1118_98_fu_2243_p0;
wire   [8:0] mul_ln1118_98_fu_2243_p1;
wire  signed [15:0] mul_ln1118_99_fu_2250_p0;
wire  signed [8:0] mul_ln1118_99_fu_2250_p1;
wire  signed [15:0] mul_ln1118_100_fu_2257_p0;
wire   [7:0] mul_ln1118_100_fu_2257_p1;
wire  signed [15:0] mul_ln1118_101_fu_2264_p0;
wire  signed [8:0] mul_ln1118_101_fu_2264_p1;
wire  signed [15:0] mul_ln1118_102_fu_2271_p0;
wire   [9:0] mul_ln1118_102_fu_2271_p1;
wire  signed [15:0] mul_ln1118_103_fu_2278_p0;
wire  signed [8:0] mul_ln1118_103_fu_2278_p1;
wire  signed [15:0] mul_ln1118_104_fu_2285_p0;
wire  signed [8:0] mul_ln1118_104_fu_2285_p1;
wire  signed [15:0] mul_ln1118_105_fu_2292_p0;
wire   [7:0] mul_ln1118_105_fu_2292_p1;
wire  signed [15:0] mul_ln1118_106_fu_2299_p0;
wire   [8:0] mul_ln1118_106_fu_2299_p1;
wire  signed [15:0] mul_ln1118_107_fu_2306_p0;
wire   [9:0] mul_ln1118_107_fu_2306_p1;
wire  signed [15:0] mul_ln1118_108_fu_2313_p0;
wire   [8:0] mul_ln1118_108_fu_2313_p1;
wire  signed [15:0] mul_ln1118_109_fu_2320_p0;
wire  signed [23:0] sext_ln1118_91_fu_376_p1;
wire  signed [7:0] mul_ln1118_109_fu_2320_p1;
wire  signed [15:0] mul_ln1118_110_fu_2327_p0;
wire  signed [8:0] mul_ln1118_110_fu_2327_p1;
wire  signed [15:0] mul_ln1118_111_fu_2334_p0;
wire   [9:0] mul_ln1118_111_fu_2334_p1;
wire  signed [15:0] mul_ln1118_112_fu_2341_p0;
wire   [7:0] mul_ln1118_112_fu_2341_p1;
wire  signed [15:0] mul_ln1118_113_fu_2348_p0;
wire   [9:0] mul_ln1118_113_fu_2348_p1;
wire  signed [15:0] mul_ln1118_114_fu_2355_p0;
wire  signed [22:0] sext_ln1118_85_fu_325_p1;
wire  signed [6:0] mul_ln1118_114_fu_2355_p1;
wire  signed [15:0] mul_ln1118_115_fu_2362_p0;
wire   [9:0] mul_ln1118_115_fu_2362_p1;
wire  signed [15:0] mul_ln1118_117_fu_2369_p0;
wire  signed [9:0] mul_ln1118_117_fu_2369_p1;
wire  signed [15:0] mul_ln1118_118_fu_2376_p0;
wire   [8:0] mul_ln1118_118_fu_2376_p1;
wire  signed [5:0] mul_ln1118_119_fu_2383_p1;
wire  signed [6:0] mul_ln1118_120_fu_2390_p1;
wire  signed [15:0] mul_ln1118_121_fu_2397_p0;
wire  signed [6:0] mul_ln1118_121_fu_2397_p1;
wire  signed [15:0] mul_ln1118_122_fu_2404_p0;
wire  signed [6:0] mul_ln1118_122_fu_2404_p1;
wire  signed [15:0] mul_ln1118_123_fu_2411_p0;
wire   [8:0] mul_ln1118_123_fu_2411_p1;
wire  signed [15:0] mul_ln1118_124_fu_2418_p0;
wire  signed [9:0] mul_ln1118_124_fu_2418_p1;
wire  signed [15:0] mul_ln1118_125_fu_2425_p0;
wire   [9:0] mul_ln1118_125_fu_2425_p1;
wire  signed [15:0] mul_ln1118_126_fu_2432_p0;
wire  signed [9:0] mul_ln1118_126_fu_2432_p1;
wire  signed [15:0] mul_ln1118_127_fu_2439_p0;
wire   [8:0] mul_ln1118_127_fu_2439_p1;
wire  signed [15:0] mul_ln1118_128_fu_2446_p0;
wire  signed [7:0] mul_ln1118_128_fu_2446_p1;
wire  signed [15:0] mul_ln1118_129_fu_2453_p0;
wire   [9:0] mul_ln1118_129_fu_2453_p1;
wire  signed [15:0] mul_ln1118_130_fu_2460_p0;
wire  signed [7:0] mul_ln1118_130_fu_2460_p1;
wire  signed [15:0] mul_ln1118_131_fu_2467_p0;
wire   [8:0] mul_ln1118_131_fu_2467_p1;
wire  signed [15:0] mul_ln1118_132_fu_2474_p0;
wire  signed [8:0] mul_ln1118_132_fu_2474_p1;
wire  signed [15:0] mul_ln1118_133_fu_2481_p0;
wire  signed [8:0] mul_ln1118_133_fu_2481_p1;
wire  signed [15:0] mul_ln1118_134_fu_2488_p0;
wire   [9:0] mul_ln1118_134_fu_2488_p1;
wire  signed [6:0] mul_ln1118_135_fu_2495_p1;
wire   [6:0] mul_ln1118_136_fu_2502_p1;
wire  signed [15:0] mul_ln1118_137_fu_2509_p0;
wire   [7:0] mul_ln1118_137_fu_2509_p1;
wire  signed [15:0] mul_ln1118_138_fu_2516_p0;
wire  signed [6:0] mul_ln1118_138_fu_2516_p1;
wire  signed [15:0] mul_ln1118_139_fu_2523_p0;
wire   [7:0] mul_ln1118_139_fu_2523_p1;
wire  signed [15:0] mul_ln1118_140_fu_2530_p0;
wire  signed [8:0] mul_ln1118_140_fu_2530_p1;
wire  signed [15:0] mul_ln1118_141_fu_2537_p0;
wire   [9:0] mul_ln1118_141_fu_2537_p1;
reg    ap_ce_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
reg   [15:0] ap_return_7_int_reg;

myproject_mul_mul_16s_7ns_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_16s_7ns_23_1_0_U1778(
    .din0(data_0_V_read),
    .din1(mul_ln1118_fu_2117_p1),
    .dout(mul_ln1118_fu_2117_p2)
);

myproject_mul_mul_16s_8s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8s_24_1_0_U1779(
    .din0(mul_ln1118_81_fu_2124_p0),
    .din1(mul_ln1118_81_fu_2124_p1),
    .dout(mul_ln1118_81_fu_2124_p2)
);

myproject_mul_mul_16s_8s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8s_24_1_0_U1780(
    .din0(mul_ln1118_82_fu_2131_p0),
    .din1(mul_ln1118_82_fu_2131_p1),
    .dout(mul_ln1118_82_fu_2131_p2)
);

myproject_mul_mul_16s_8ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8ns_24_1_0_U1781(
    .din0(mul_ln1118_83_fu_2138_p0),
    .din1(mul_ln1118_83_fu_2138_p1),
    .dout(mul_ln1118_83_fu_2138_p2)
);

myproject_mul_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9ns_24_1_0_U1782(
    .din0(mul_ln1118_84_fu_2145_p0),
    .din1(mul_ln1118_84_fu_2145_p1),
    .dout(mul_ln1118_84_fu_2145_p2)
);

myproject_mul_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9ns_24_1_0_U1783(
    .din0(mul_ln1118_85_fu_2152_p0),
    .din1(mul_ln1118_85_fu_2152_p1),
    .dout(mul_ln1118_85_fu_2152_p2)
);

myproject_mul_mul_16s_10s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10s_24_1_0_U1784(
    .din0(mul_ln1118_86_fu_2159_p0),
    .din1(mul_ln1118_86_fu_2159_p1),
    .dout(mul_ln1118_86_fu_2159_p2)
);

myproject_mul_mul_16s_8ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8ns_24_1_0_U1785(
    .din0(mul_ln1118_87_fu_2166_p0),
    .din1(mul_ln1118_87_fu_2166_p1),
    .dout(mul_ln1118_87_fu_2166_p2)
);

myproject_mul_mul_16s_9s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9s_24_1_0_U1786(
    .din0(mul_ln1118_88_fu_2173_p0),
    .din1(mul_ln1118_88_fu_2173_p1),
    .dout(mul_ln1118_88_fu_2173_p2)
);

myproject_mul_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9ns_24_1_0_U1787(
    .din0(mul_ln1118_89_fu_2180_p0),
    .din1(mul_ln1118_89_fu_2180_p1),
    .dout(mul_ln1118_89_fu_2180_p2)
);

myproject_mul_mul_16s_8s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8s_24_1_0_U1788(
    .din0(mul_ln1118_90_fu_2187_p0),
    .din1(mul_ln1118_90_fu_2187_p1),
    .dout(mul_ln1118_90_fu_2187_p2)
);

myproject_mul_mul_16s_10ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10ns_24_1_0_U1789(
    .din0(mul_ln1118_91_fu_2194_p0),
    .din1(mul_ln1118_91_fu_2194_p1),
    .dout(mul_ln1118_91_fu_2194_p2)
);

myproject_mul_mul_16s_7s_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_16s_7s_23_1_0_U1790(
    .din0(data_3_V_read),
    .din1(mul_ln1118_92_fu_2201_p1),
    .dout(mul_ln1118_92_fu_2201_p2)
);

myproject_mul_mul_16s_7ns_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_16s_7ns_23_1_0_U1791(
    .din0(mul_ln1118_93_fu_2208_p0),
    .din1(mul_ln1118_93_fu_2208_p1),
    .dout(mul_ln1118_93_fu_2208_p2)
);

myproject_mul_mul_16s_9s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9s_24_1_0_U1792(
    .din0(mul_ln1118_94_fu_2215_p0),
    .din1(mul_ln1118_94_fu_2215_p1),
    .dout(mul_ln1118_94_fu_2215_p2)
);

myproject_mul_mul_16s_8s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8s_24_1_0_U1793(
    .din0(mul_ln1118_95_fu_2222_p0),
    .din1(mul_ln1118_95_fu_2222_p1),
    .dout(mul_ln1118_95_fu_2222_p2)
);

myproject_mul_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9ns_24_1_0_U1794(
    .din0(mul_ln1118_96_fu_2229_p0),
    .din1(mul_ln1118_96_fu_2229_p1),
    .dout(mul_ln1118_96_fu_2229_p2)
);

myproject_mul_mul_16s_8s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8s_24_1_0_U1795(
    .din0(mul_ln1118_97_fu_2236_p0),
    .din1(mul_ln1118_97_fu_2236_p1),
    .dout(mul_ln1118_97_fu_2236_p2)
);

myproject_mul_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9ns_24_1_0_U1796(
    .din0(mul_ln1118_98_fu_2243_p0),
    .din1(mul_ln1118_98_fu_2243_p1),
    .dout(mul_ln1118_98_fu_2243_p2)
);

myproject_mul_mul_16s_9s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9s_24_1_0_U1797(
    .din0(mul_ln1118_99_fu_2250_p0),
    .din1(mul_ln1118_99_fu_2250_p1),
    .dout(mul_ln1118_99_fu_2250_p2)
);

myproject_mul_mul_16s_8ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8ns_24_1_0_U1798(
    .din0(mul_ln1118_100_fu_2257_p0),
    .din1(mul_ln1118_100_fu_2257_p1),
    .dout(mul_ln1118_100_fu_2257_p2)
);

myproject_mul_mul_16s_9s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9s_24_1_0_U1799(
    .din0(mul_ln1118_101_fu_2264_p0),
    .din1(mul_ln1118_101_fu_2264_p1),
    .dout(mul_ln1118_101_fu_2264_p2)
);

myproject_mul_mul_16s_10ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10ns_24_1_0_U1800(
    .din0(mul_ln1118_102_fu_2271_p0),
    .din1(mul_ln1118_102_fu_2271_p1),
    .dout(mul_ln1118_102_fu_2271_p2)
);

myproject_mul_mul_16s_9s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9s_24_1_0_U1801(
    .din0(mul_ln1118_103_fu_2278_p0),
    .din1(mul_ln1118_103_fu_2278_p1),
    .dout(mul_ln1118_103_fu_2278_p2)
);

myproject_mul_mul_16s_9s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9s_24_1_0_U1802(
    .din0(mul_ln1118_104_fu_2285_p0),
    .din1(mul_ln1118_104_fu_2285_p1),
    .dout(mul_ln1118_104_fu_2285_p2)
);

myproject_mul_mul_16s_8ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8ns_24_1_0_U1803(
    .din0(mul_ln1118_105_fu_2292_p0),
    .din1(mul_ln1118_105_fu_2292_p1),
    .dout(mul_ln1118_105_fu_2292_p2)
);

myproject_mul_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9ns_24_1_0_U1804(
    .din0(mul_ln1118_106_fu_2299_p0),
    .din1(mul_ln1118_106_fu_2299_p1),
    .dout(mul_ln1118_106_fu_2299_p2)
);

myproject_mul_mul_16s_10ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10ns_24_1_0_U1805(
    .din0(mul_ln1118_107_fu_2306_p0),
    .din1(mul_ln1118_107_fu_2306_p1),
    .dout(mul_ln1118_107_fu_2306_p2)
);

myproject_mul_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9ns_24_1_0_U1806(
    .din0(mul_ln1118_108_fu_2313_p0),
    .din1(mul_ln1118_108_fu_2313_p1),
    .dout(mul_ln1118_108_fu_2313_p2)
);

myproject_mul_mul_16s_8s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8s_24_1_0_U1807(
    .din0(mul_ln1118_109_fu_2320_p0),
    .din1(mul_ln1118_109_fu_2320_p1),
    .dout(mul_ln1118_109_fu_2320_p2)
);

myproject_mul_mul_16s_9s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9s_24_1_0_U1808(
    .din0(mul_ln1118_110_fu_2327_p0),
    .din1(mul_ln1118_110_fu_2327_p1),
    .dout(mul_ln1118_110_fu_2327_p2)
);

myproject_mul_mul_16s_10ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10ns_24_1_0_U1809(
    .din0(mul_ln1118_111_fu_2334_p0),
    .din1(mul_ln1118_111_fu_2334_p1),
    .dout(mul_ln1118_111_fu_2334_p2)
);

myproject_mul_mul_16s_8ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8ns_24_1_0_U1810(
    .din0(mul_ln1118_112_fu_2341_p0),
    .din1(mul_ln1118_112_fu_2341_p1),
    .dout(mul_ln1118_112_fu_2341_p2)
);

myproject_mul_mul_16s_10ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10ns_24_1_0_U1811(
    .din0(mul_ln1118_113_fu_2348_p0),
    .din1(mul_ln1118_113_fu_2348_p1),
    .dout(mul_ln1118_113_fu_2348_p2)
);

myproject_mul_mul_16s_7s_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_16s_7s_23_1_0_U1812(
    .din0(mul_ln1118_114_fu_2355_p0),
    .din1(mul_ln1118_114_fu_2355_p1),
    .dout(mul_ln1118_114_fu_2355_p2)
);

myproject_mul_mul_16s_10ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10ns_24_1_0_U1813(
    .din0(mul_ln1118_115_fu_2362_p0),
    .din1(mul_ln1118_115_fu_2362_p1),
    .dout(mul_ln1118_115_fu_2362_p2)
);

myproject_mul_mul_16s_10s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10s_24_1_0_U1814(
    .din0(mul_ln1118_117_fu_2369_p0),
    .din1(mul_ln1118_117_fu_2369_p1),
    .dout(mul_ln1118_117_fu_2369_p2)
);

myproject_mul_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9ns_24_1_0_U1815(
    .din0(mul_ln1118_118_fu_2376_p0),
    .din1(mul_ln1118_118_fu_2376_p1),
    .dout(mul_ln1118_118_fu_2376_p2)
);

myproject_mul_mul_16s_6s_22_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 22 ))
myproject_mul_mul_16s_6s_22_1_0_U1816(
    .din0(data_1_V_read),
    .din1(mul_ln1118_119_fu_2383_p1),
    .dout(mul_ln1118_119_fu_2383_p2)
);

myproject_mul_mul_16s_7s_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_16s_7s_23_1_0_U1817(
    .din0(data_2_V_read),
    .din1(mul_ln1118_120_fu_2390_p1),
    .dout(mul_ln1118_120_fu_2390_p2)
);

myproject_mul_mul_16s_7s_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_16s_7s_23_1_0_U1818(
    .din0(mul_ln1118_121_fu_2397_p0),
    .din1(mul_ln1118_121_fu_2397_p1),
    .dout(mul_ln1118_121_fu_2397_p2)
);

myproject_mul_mul_16s_7s_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_16s_7s_23_1_0_U1819(
    .din0(mul_ln1118_122_fu_2404_p0),
    .din1(mul_ln1118_122_fu_2404_p1),
    .dout(mul_ln1118_122_fu_2404_p2)
);

myproject_mul_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9ns_24_1_0_U1820(
    .din0(mul_ln1118_123_fu_2411_p0),
    .din1(mul_ln1118_123_fu_2411_p1),
    .dout(mul_ln1118_123_fu_2411_p2)
);

myproject_mul_mul_16s_10s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10s_24_1_0_U1821(
    .din0(mul_ln1118_124_fu_2418_p0),
    .din1(mul_ln1118_124_fu_2418_p1),
    .dout(mul_ln1118_124_fu_2418_p2)
);

myproject_mul_mul_16s_10ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10ns_24_1_0_U1822(
    .din0(mul_ln1118_125_fu_2425_p0),
    .din1(mul_ln1118_125_fu_2425_p1),
    .dout(mul_ln1118_125_fu_2425_p2)
);

myproject_mul_mul_16s_10s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10s_24_1_0_U1823(
    .din0(mul_ln1118_126_fu_2432_p0),
    .din1(mul_ln1118_126_fu_2432_p1),
    .dout(mul_ln1118_126_fu_2432_p2)
);

myproject_mul_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9ns_24_1_0_U1824(
    .din0(mul_ln1118_127_fu_2439_p0),
    .din1(mul_ln1118_127_fu_2439_p1),
    .dout(mul_ln1118_127_fu_2439_p2)
);

myproject_mul_mul_16s_8s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8s_24_1_0_U1825(
    .din0(mul_ln1118_128_fu_2446_p0),
    .din1(mul_ln1118_128_fu_2446_p1),
    .dout(mul_ln1118_128_fu_2446_p2)
);

myproject_mul_mul_16s_10ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10ns_24_1_0_U1826(
    .din0(mul_ln1118_129_fu_2453_p0),
    .din1(mul_ln1118_129_fu_2453_p1),
    .dout(mul_ln1118_129_fu_2453_p2)
);

myproject_mul_mul_16s_8s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8s_24_1_0_U1827(
    .din0(mul_ln1118_130_fu_2460_p0),
    .din1(mul_ln1118_130_fu_2460_p1),
    .dout(mul_ln1118_130_fu_2460_p2)
);

myproject_mul_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9ns_24_1_0_U1828(
    .din0(mul_ln1118_131_fu_2467_p0),
    .din1(mul_ln1118_131_fu_2467_p1),
    .dout(mul_ln1118_131_fu_2467_p2)
);

myproject_mul_mul_16s_9s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9s_24_1_0_U1829(
    .din0(mul_ln1118_132_fu_2474_p0),
    .din1(mul_ln1118_132_fu_2474_p1),
    .dout(mul_ln1118_132_fu_2474_p2)
);

myproject_mul_mul_16s_9s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9s_24_1_0_U1830(
    .din0(mul_ln1118_133_fu_2481_p0),
    .din1(mul_ln1118_133_fu_2481_p1),
    .dout(mul_ln1118_133_fu_2481_p2)
);

myproject_mul_mul_16s_10ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10ns_24_1_0_U1831(
    .din0(mul_ln1118_134_fu_2488_p0),
    .din1(mul_ln1118_134_fu_2488_p1),
    .dout(mul_ln1118_134_fu_2488_p2)
);

myproject_mul_mul_16s_7s_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_16s_7s_23_1_0_U1832(
    .din0(data_8_V_read),
    .din1(mul_ln1118_135_fu_2495_p1),
    .dout(mul_ln1118_135_fu_2495_p2)
);

myproject_mul_mul_16s_7ns_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_16s_7ns_23_1_0_U1833(
    .din0(data_9_V_read),
    .din1(mul_ln1118_136_fu_2502_p1),
    .dout(mul_ln1118_136_fu_2502_p2)
);

myproject_mul_mul_16s_8ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8ns_24_1_0_U1834(
    .din0(mul_ln1118_137_fu_2509_p0),
    .din1(mul_ln1118_137_fu_2509_p1),
    .dout(mul_ln1118_137_fu_2509_p2)
);

myproject_mul_mul_16s_7s_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_16s_7s_23_1_0_U1835(
    .din0(mul_ln1118_138_fu_2516_p0),
    .din1(mul_ln1118_138_fu_2516_p1),
    .dout(mul_ln1118_138_fu_2516_p2)
);

myproject_mul_mul_16s_8ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_8ns_24_1_0_U1836(
    .din0(mul_ln1118_139_fu_2523_p0),
    .din1(mul_ln1118_139_fu_2523_p1),
    .dout(mul_ln1118_139_fu_2523_p2)
);

myproject_mul_mul_16s_9s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_9s_24_1_0_U1837(
    .din0(mul_ln1118_140_fu_2530_p0),
    .din1(mul_ln1118_140_fu_2530_p1),
    .dout(mul_ln1118_140_fu_2530_p2)
);

myproject_mul_mul_16s_10ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 24 ))
myproject_mul_mul_16s_10ns_24_1_0_U1838(
    .din0(mul_ln1118_141_fu_2537_p0),
    .din1(mul_ln1118_141_fu_2537_p1),
    .dout(mul_ln1118_141_fu_2537_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        add_ln703_183_reg_2544 <= add_ln703_183_fu_515_p2;
        add_ln703_185_reg_2549 <= add_ln703_185_fu_527_p2;
        add_ln703_187_reg_2554 <= add_ln703_187_fu_539_p2;
        add_ln703_193_reg_2559 <= add_ln703_193_fu_688_p2;
        add_ln703_195_reg_2564 <= add_ln703_195_fu_700_p2;
        add_ln703_197_reg_2569 <= add_ln703_197_fu_712_p2;
        add_ln703_203_reg_2574 <= add_ln703_203_fu_866_p2;
        add_ln703_205_reg_2579 <= add_ln703_205_fu_878_p2;
        add_ln703_207_reg_2584 <= add_ln703_207_fu_890_p2;
        add_ln703_213_reg_2589 <= add_ln703_213_fu_1105_p2;
        add_ln703_215_reg_2594 <= add_ln703_215_fu_1117_p2;
        add_ln703_217_reg_2599 <= add_ln703_217_fu_1129_p2;
        add_ln703_223_reg_2604 <= add_ln703_223_fu_1380_p2;
        add_ln703_225_reg_2609 <= add_ln703_225_fu_1392_p2;
        add_ln703_227_reg_2614 <= add_ln703_227_fu_1404_p2;
        add_ln703_233_reg_2619 <= add_ln703_233_fu_1562_p2;
        add_ln703_235_reg_2624 <= add_ln703_235_fu_1574_p2;
        add_ln703_237_reg_2629 <= add_ln703_237_fu_1590_p2;
        add_ln703_243_reg_2634 <= add_ln703_243_fu_1712_p2;
        add_ln703_245_reg_2639 <= add_ln703_245_fu_1724_p2;
        add_ln703_247_reg_2644 <= add_ln703_247_fu_1736_p2;
        add_ln703_253_reg_2649 <= add_ln703_253_fu_1963_p2;
        add_ln703_255_reg_2654 <= add_ln703_255_fu_1975_p2;
        add_ln703_257_reg_2659 <= add_ln703_257_fu_1991_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln703_189_fu_2001_p2;
        ap_return_1_int_reg <= acc_1_V_fu_2010_p2;
        ap_return_2_int_reg <= acc_2_V_fu_2019_p2;
        ap_return_3_int_reg <= acc_3_V_fu_2028_p2;
        ap_return_4_int_reg <= acc_4_V_fu_2037_p2;
        ap_return_5_int_reg <= acc_5_V_fu_2046_p2;
        ap_return_6_int_reg <= acc_6_V_fu_2055_p2;
        ap_return_7_int_reg <= acc_7_V_fu_2064_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln703_189_fu_2001_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = acc_1_V_fu_2010_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = acc_2_V_fu_2019_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = acc_3_V_fu_2028_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = acc_4_V_fu_2037_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = acc_5_V_fu_2046_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = acc_6_V_fu_2055_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = acc_7_V_fu_2064_p2;
    end
end

assign acc_1_V_fu_2010_p2 = (add_ln703_193_reg_2559 + add_ln703_198_fu_2006_p2);

assign acc_2_V_fu_2019_p2 = (add_ln703_203_reg_2574 + add_ln703_208_fu_2015_p2);

assign acc_3_V_fu_2028_p2 = (add_ln703_213_reg_2589 + add_ln703_218_fu_2024_p2);

assign acc_4_V_fu_2037_p2 = (add_ln703_223_reg_2604 + add_ln703_228_fu_2033_p2);

assign acc_5_V_fu_2046_p2 = (add_ln703_233_reg_2619 + add_ln703_238_fu_2042_p2);

assign acc_6_V_fu_2055_p2 = (add_ln703_243_reg_2634 + add_ln703_248_fu_2051_p2);

assign acc_7_V_fu_2064_p2 = (add_ln703_253_reg_2649 + add_ln703_258_fu_2060_p2);

assign add_ln1118_4_fu_783_p2 = ($signed(sext_ln1118_104_fu_767_p1) + $signed(sext_ln1118_105_fu_779_p1));

assign add_ln1118_5_fu_1058_p2 = ($signed(sext_ln1118_109_fu_1038_p1) + $signed(sext_ln1118_111_fu_1054_p1));

assign add_ln1118_6_fu_1338_p2 = ($signed(sext_ln1118_118_fu_1322_p1) + $signed(sext_ln1118_119_fu_1334_p1));

assign add_ln1118_7_fu_1907_p2 = ($signed(sext_ln1118_116_fu_1272_p1) + $signed(sext_ln1118_110_fu_1050_p1));

assign add_ln1118_fu_654_p2 = ($signed(shl_ln_fu_634_p3) + $signed(sext_ln1118_103_fu_650_p1));

assign add_ln703_181_fu_503_p2 = ($signed(sext_ln708_54_fu_416_p1) + $signed(trunc_ln708_100_fu_367_p4));

assign add_ln703_182_fu_509_p2 = (trunc_ln708_99_fu_346_p4 + add_ln703_181_fu_503_p2);

assign add_ln703_183_fu_515_p2 = (add_ln703_fu_497_p2 + add_ln703_182_fu_509_p2);

assign add_ln703_184_fu_521_p2 = (trunc_ln708_104_fu_454_p4 + trunc_ln708_103_fu_441_p4);

assign add_ln703_185_fu_527_p2 = (trunc_ln708_102_fu_428_p4 + add_ln703_184_fu_521_p2);

assign add_ln703_186_fu_533_p2 = (trunc_ln708_106_fu_488_p4 + 16'd200);

assign add_ln703_187_fu_539_p2 = (trunc_ln708_105_fu_471_p4 + add_ln703_186_fu_533_p2);

assign add_ln703_188_fu_1997_p2 = (add_ln703_185_reg_2549 + add_ln703_187_reg_2554);

assign add_ln703_189_fu_2001_p2 = (add_ln703_183_reg_2544 + add_ln703_188_fu_1997_p2);

assign add_ln703_190_fu_670_p2 = (trunc_ln708_108_fu_554_p4 + trunc_ln708_107_fu_545_p4);

assign add_ln703_191_fu_676_p2 = ($signed(sext_ln708_56_fu_594_p1) + $signed(sext_ln708_55_fu_581_p1));

assign add_ln703_192_fu_682_p2 = (trunc_ln708_109_fu_563_p4 + add_ln703_191_fu_676_p2);

assign add_ln703_193_fu_688_p2 = (add_ln703_190_fu_670_p2 + add_ln703_192_fu_682_p2);

assign add_ln703_194_fu_694_p2 = (trunc_ln708_114_fu_616_p4 + trunc_ln708_113_fu_607_p4);

assign add_ln703_195_fu_700_p2 = (trunc_ln708_112_fu_598_p4 + add_ln703_194_fu_694_p2);

assign add_ln703_196_fu_706_p2 = ($signed(trunc_ln708_116_fu_660_p4) + $signed(16'd65421));

assign add_ln703_197_fu_712_p2 = (trunc_ln708_115_fu_625_p4 + add_ln703_196_fu_706_p2);

assign add_ln703_198_fu_2006_p2 = (add_ln703_195_reg_2564 + add_ln703_197_reg_2569);

assign add_ln703_200_fu_848_p2 = (trunc_ln708_118_fu_727_p4 + trunc_ln708_117_fu_718_p4);

assign add_ln703_201_fu_854_p2 = ($signed(sext_ln708_58_fu_799_p1) + $signed(trunc_ln708_120_fu_750_p4));

assign add_ln703_202_fu_860_p2 = ($signed(sext_ln708_57_fu_746_p1) + $signed(add_ln703_201_fu_854_p2));

assign add_ln703_203_fu_866_p2 = (add_ln703_200_fu_848_p2 + add_ln703_202_fu_860_p2);

assign add_ln703_204_fu_872_p2 = (trunc_ln708_124_fu_821_p4 + trunc_ln708_123_fu_812_p4);

assign add_ln703_205_fu_878_p2 = (trunc_ln708_122_fu_803_p4 + add_ln703_204_fu_872_p2);

assign add_ln703_206_fu_884_p2 = ($signed(trunc_ln708_126_fu_839_p4) + $signed(16'd65390));

assign add_ln703_207_fu_890_p2 = (trunc_ln708_125_fu_830_p4 + add_ln703_206_fu_884_p2);

assign add_ln703_208_fu_2015_p2 = (add_ln703_205_reg_2579 + add_ln703_207_reg_2584);

assign add_ln703_210_fu_1087_p2 = ($signed(sext_ln708_59_fu_945_p1) + $signed(trunc_ln708_127_fu_896_p4));

assign add_ln703_211_fu_1093_p2 = (trunc_ln708_131_fu_967_p4 + trunc_ln708_130_fu_958_p4);

assign add_ln703_212_fu_1099_p2 = (trunc_ln708_129_fu_949_p4 + add_ln703_211_fu_1093_p2);

assign add_ln703_213_fu_1105_p2 = (add_ln703_210_fu_1087_p2 + add_ln703_212_fu_1099_p2);

assign add_ln703_214_fu_1111_p2 = (trunc_ln708_134_fu_1021_p4 + trunc_ln708_133_fu_1012_p4);

assign add_ln703_215_fu_1117_p2 = (trunc_ln708_132_fu_1002_p4 + add_ln703_214_fu_1111_p2);

assign add_ln703_216_fu_1123_p2 = (trunc_ln708_136_fu_1078_p4 + 16'd106);

assign add_ln703_217_fu_1129_p2 = ($signed(sext_ln708_60_fu_1074_p1) + $signed(add_ln703_216_fu_1123_p2));

assign add_ln703_218_fu_2024_p2 = (add_ln703_215_reg_2594 + add_ln703_217_reg_2599);

assign add_ln703_220_fu_1358_p2 = ($signed(sext_ln708_61_fu_1153_p1) + $signed(trunc_ln708_137_fu_1135_p4));

assign add_ln703_221_fu_1364_p2 = ($signed(sext_ln1118_127_fu_1218_p1) + $signed(sext_ln1118_112_fu_1182_p1));

assign add_ln703_222_fu_1374_p2 = ($signed(trunc_ln708_139_fu_1157_p4) + $signed(sext_ln703_fu_1370_p1));

assign add_ln703_223_fu_1380_p2 = (add_ln703_220_fu_1358_p2 + add_ln703_222_fu_1374_p2);

assign add_ln703_224_fu_1386_p2 = (trunc_ln708_142_fu_1255_p4 + trunc_ln708_141_fu_1246_p4);

assign add_ln703_225_fu_1392_p2 = ($signed(sext_ln708_62_fu_1242_p1) + $signed(add_ln703_224_fu_1386_p2));

assign add_ln703_226_fu_1398_p2 = ($signed(sext_ln708_64_fu_1354_p1) + $signed(16'd156));

assign add_ln703_227_fu_1404_p2 = ($signed(sext_ln708_63_fu_1310_p1) + $signed(add_ln703_226_fu_1398_p2));

assign add_ln703_228_fu_2033_p2 = (add_ln703_225_reg_2609 + add_ln703_227_reg_2614);

assign add_ln703_230_fu_1544_p2 = ($signed(sext_ln708_66_fu_1446_p1) + $signed(sext_ln708_65_fu_1433_p1));

assign add_ln703_231_fu_1550_p2 = ($signed(sext_ln708_69_fu_1504_p1) + $signed(sext_ln708_68_fu_1491_p1));

assign add_ln703_232_fu_1556_p2 = ($signed(sext_ln708_67_fu_1478_p1) + $signed(add_ln703_231_fu_1550_p2));

assign add_ln703_233_fu_1562_p2 = (add_ln703_230_fu_1544_p2 + add_ln703_232_fu_1556_p2);

assign add_ln703_234_fu_1568_p2 = (trunc_ln708_153_fu_1526_p4 + trunc_ln708_152_fu_1517_p4);

assign add_ln703_235_fu_1574_p2 = (trunc_ln708_151_fu_1508_p4 + add_ln703_234_fu_1568_p2);

assign add_ln703_236_fu_1580_p2 = ($signed(sext_ln1118_120_fu_1420_p1) + $signed(9'd282));

assign add_ln703_237_fu_1590_p2 = (trunc_ln708_154_fu_1535_p4 + zext_ln703_fu_1586_p1);

assign add_ln703_238_fu_2042_p2 = (add_ln703_235_reg_2624 + add_ln703_237_reg_2629);

assign add_ln703_240_fu_1694_p2 = (trunc_ln708_156_fu_1605_p4 + trunc_ln708_155_fu_1596_p4);

assign add_ln703_241_fu_1700_p2 = (trunc_ln708_159_fu_1632_p4 + trunc_ln708_158_fu_1623_p4);

assign add_ln703_242_fu_1706_p2 = (trunc_ln708_157_fu_1614_p4 + add_ln703_241_fu_1700_p2);

assign add_ln703_243_fu_1712_p2 = (add_ln703_240_fu_1694_p2 + add_ln703_242_fu_1706_p2);

assign add_ln703_244_fu_1718_p2 = (trunc_ln708_162_fu_1659_p4 + trunc_ln708_161_fu_1650_p4);

assign add_ln703_245_fu_1724_p2 = (trunc_ln708_160_fu_1641_p4 + add_ln703_244_fu_1718_p2);

assign add_ln703_246_fu_1730_p2 = ($signed(sext_ln708_71_fu_1690_p1) + $signed(16'd143));

assign add_ln703_247_fu_1736_p2 = ($signed(sext_ln708_70_fu_1677_p1) + $signed(add_ln703_246_fu_1730_p2));

assign add_ln703_248_fu_2051_p2 = (add_ln703_245_reg_2639 + add_ln703_247_reg_2644);

assign add_ln703_250_fu_1941_p2 = ($signed(sext_ln708_72_fu_1760_p1) + $signed(trunc_ln708_165_fu_1742_p4));

assign add_ln703_251_fu_1947_p2 = ($signed(sext_ln1118_129_fu_1876_p1) + $signed(sext_ln1118_128_fu_1844_p1));

assign add_ln703_252_fu_1957_p2 = ($signed(trunc_ln708_167_fu_1794_p4) + $signed(sext_ln703_12_fu_1953_p1));

assign add_ln703_253_fu_1963_p2 = (add_ln703_250_fu_1941_p2 + add_ln703_252_fu_1957_p2);

assign add_ln703_254_fu_1969_p2 = (trunc_ln708_170_fu_1898_p4 + trunc_ln708_169_fu_1889_p4);

assign add_ln703_255_fu_1975_p2 = (trunc_ln708_168_fu_1880_p4 + add_ln703_254_fu_1969_p2);

assign add_ln703_256_fu_1981_p2 = ($signed(sext_ln703_11_fu_1937_p1) + $signed(15'd32710));

assign add_ln703_257_fu_1991_p2 = ($signed(sext_ln708_73_fu_1923_p1) + $signed(sext_ln703_13_fu_1987_p1));

assign add_ln703_258_fu_2060_p2 = (add_ln703_255_reg_2654 + add_ln703_257_reg_2659);

assign add_ln703_fu_497_p2 = ($signed(trunc_ln708_s_fu_329_p4) + $signed(sext_ln708_fu_313_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign mul_ln1118_100_fu_2257_p0 = sext_ln1118_88_fu_355_p1;

assign mul_ln1118_100_fu_2257_p1 = 24'd76;

assign mul_ln1118_101_fu_2264_p0 = sext_ln1118_95_fu_420_p1;

assign mul_ln1118_101_fu_2264_p1 = 24'd16777068;

assign mul_ln1118_102_fu_2271_p0 = sext_ln1118_97_fu_437_p1;

assign mul_ln1118_102_fu_2271_p1 = 24'd312;

assign mul_ln1118_103_fu_2278_p0 = sext_ln1118_98_fu_450_p1;

assign mul_ln1118_103_fu_2278_p1 = 24'd16777078;

assign mul_ln1118_104_fu_2285_p0 = sext_ln1118_99_fu_463_p1;

assign mul_ln1118_104_fu_2285_p1 = 24'd16777057;

assign mul_ln1118_105_fu_2292_p0 = sext_ln1118_101_fu_480_p1;

assign mul_ln1118_105_fu_2292_p1 = 24'd100;

assign mul_ln1118_106_fu_2299_p0 = sext_ln1118_fu_296_p1;

assign mul_ln1118_106_fu_2299_p1 = 24'd191;

assign mul_ln1118_107_fu_2306_p0 = sext_ln1118_86_fu_338_p1;

assign mul_ln1118_107_fu_2306_p1 = 24'd304;

assign mul_ln1118_108_fu_2313_p0 = sext_ln1118_88_fu_355_p1;

assign mul_ln1118_108_fu_2313_p1 = 24'd170;

assign mul_ln1118_109_fu_2320_p0 = sext_ln1118_91_fu_376_p1;

assign mul_ln1118_109_fu_2320_p1 = 24'd16777121;

assign mul_ln1118_110_fu_2327_p0 = sext_ln1118_97_fu_437_p1;

assign mul_ln1118_110_fu_2327_p1 = 24'd16776983;

assign mul_ln1118_111_fu_2334_p0 = sext_ln1118_98_fu_450_p1;

assign mul_ln1118_111_fu_2334_p1 = 24'd315;

assign mul_ln1118_112_fu_2341_p0 = sext_ln1118_101_fu_480_p1;

assign mul_ln1118_112_fu_2341_p1 = 24'd97;

assign mul_ln1118_113_fu_2348_p0 = sext_ln1118_fu_296_p1;

assign mul_ln1118_113_fu_2348_p1 = 24'd265;

assign mul_ln1118_114_fu_2355_p0 = sext_ln1118_85_fu_325_p1;

assign mul_ln1118_114_fu_2355_p1 = 23'd8388561;

assign mul_ln1118_115_fu_2362_p0 = sext_ln1118_86_fu_338_p1;

assign mul_ln1118_115_fu_2362_p1 = 24'd311;

assign mul_ln1118_116_fu_1166_p0 = sext_ln1118_90_fu_363_p0;

assign mul_ln1118_116_fu_1166_p2 = ($signed(mul_ln1118_116_fu_1166_p0) * $signed('hB));

assign mul_ln1118_117_fu_2369_p0 = sext_ln1118_97_fu_437_p1;

assign mul_ln1118_117_fu_2369_p1 = 24'd16776923;

assign mul_ln1118_118_fu_2376_p0 = sext_ln1118_98_fu_450_p1;

assign mul_ln1118_118_fu_2376_p1 = 24'd201;

assign mul_ln1118_119_fu_2383_p1 = 22'd4194281;

assign mul_ln1118_120_fu_2390_p1 = 23'd8388573;

assign mul_ln1118_121_fu_2397_p0 = sext_ln1118_92_fu_380_p1;

assign mul_ln1118_121_fu_2397_p1 = 23'd8388570;

assign mul_ln1118_122_fu_2404_p0 = sext_ln1118_96_fu_424_p1;

assign mul_ln1118_122_fu_2404_p1 = 23'd8388555;

assign mul_ln1118_123_fu_2411_p0 = sext_ln1118_97_fu_437_p1;

assign mul_ln1118_123_fu_2411_p1 = 24'd210;

assign mul_ln1118_124_fu_2418_p0 = sext_ln1118_98_fu_450_p1;

assign mul_ln1118_124_fu_2418_p1 = 24'd16776885;

assign mul_ln1118_125_fu_2425_p0 = sext_ln1118_99_fu_463_p1;

assign mul_ln1118_125_fu_2425_p1 = 24'd326;

assign mul_ln1118_126_fu_2432_p0 = sext_ln1118_101_fu_480_p1;

assign mul_ln1118_126_fu_2432_p1 = 24'd16776872;

assign mul_ln1118_127_fu_2439_p0 = sext_ln1118_fu_296_p1;

assign mul_ln1118_127_fu_2439_p1 = 24'd138;

assign mul_ln1118_128_fu_2446_p0 = sext_ln1118_83_fu_317_p1;

assign mul_ln1118_128_fu_2446_p1 = 24'd16777119;

assign mul_ln1118_129_fu_2453_p0 = sext_ln1118_86_fu_338_p1;

assign mul_ln1118_129_fu_2453_p1 = 24'd337;

assign mul_ln1118_130_fu_2460_p0 = sext_ln1118_88_fu_355_p1;

assign mul_ln1118_130_fu_2460_p1 = 24'd16777127;

assign mul_ln1118_131_fu_2467_p0 = sext_ln1118_91_fu_376_p1;

assign mul_ln1118_131_fu_2467_p1 = 24'd146;

assign mul_ln1118_132_fu_2474_p0 = sext_ln1118_95_fu_420_p1;

assign mul_ln1118_132_fu_2474_p1 = 24'd16777077;

assign mul_ln1118_133_fu_2481_p0 = sext_ln1118_97_fu_437_p1;

assign mul_ln1118_133_fu_2481_p1 = 24'd16776999;

assign mul_ln1118_134_fu_2488_p0 = sext_ln1118_98_fu_450_p1;

assign mul_ln1118_134_fu_2488_p1 = 24'd266;

assign mul_ln1118_135_fu_2495_p1 = 23'd8388565;

assign mul_ln1118_136_fu_2502_p1 = 23'd57;

assign mul_ln1118_137_fu_2509_p0 = sext_ln1118_fu_296_p1;

assign mul_ln1118_137_fu_2509_p1 = 24'd87;

assign mul_ln1118_138_fu_2516_p0 = sext_ln1118_85_fu_325_p1;

assign mul_ln1118_138_fu_2516_p1 = 23'd8388547;

assign mul_ln1118_139_fu_2523_p0 = sext_ln1118_95_fu_420_p1;

assign mul_ln1118_139_fu_2523_p1 = 24'd103;

assign mul_ln1118_140_fu_2530_p0 = sext_ln1118_97_fu_437_p1;

assign mul_ln1118_140_fu_2530_p1 = 24'd16776973;

assign mul_ln1118_141_fu_2537_p0 = sext_ln1118_98_fu_450_p1;

assign mul_ln1118_141_fu_2537_p1 = 24'd278;

assign mul_ln1118_81_fu_2124_p0 = sext_ln1118_83_fu_317_p1;

assign mul_ln1118_81_fu_2124_p1 = 24'd16777109;

assign mul_ln1118_82_fu_2131_p0 = sext_ln1118_86_fu_338_p1;

assign mul_ln1118_82_fu_2131_p1 = 24'd16777107;

assign mul_ln1118_83_fu_2138_p0 = sext_ln1118_88_fu_355_p1;

assign mul_ln1118_83_fu_2138_p1 = 24'd101;

assign mul_ln1118_84_fu_2145_p0 = sext_ln1118_95_fu_420_p1;

assign mul_ln1118_84_fu_2145_p1 = 24'd189;

assign mul_ln1118_85_fu_2152_p0 = sext_ln1118_97_fu_437_p1;

assign mul_ln1118_85_fu_2152_p1 = 24'd156;

assign mul_ln1118_86_fu_2159_p0 = sext_ln1118_98_fu_450_p1;

assign mul_ln1118_86_fu_2159_p1 = 24'd16776933;

assign mul_ln1118_87_fu_2166_p0 = sext_ln1118_99_fu_463_p1;

assign mul_ln1118_87_fu_2166_p1 = 24'd115;

assign mul_ln1118_88_fu_2173_p0 = sext_ln1118_101_fu_480_p1;

assign mul_ln1118_88_fu_2173_p1 = 24'd16777021;

assign mul_ln1118_89_fu_2180_p0 = sext_ln1118_fu_296_p1;

assign mul_ln1118_89_fu_2180_p1 = 24'd221;

assign mul_ln1118_90_fu_2187_p0 = sext_ln1118_83_fu_317_p1;

assign mul_ln1118_90_fu_2187_p1 = 24'd16777117;

assign mul_ln1118_91_fu_2194_p0 = sext_ln1118_86_fu_338_p1;

assign mul_ln1118_91_fu_2194_p1 = 24'd355;

assign mul_ln1118_92_fu_2201_p1 = 23'd8388562;

assign mul_ln1118_93_fu_2208_p0 = sext_ln1118_92_fu_380_p1;

assign mul_ln1118_93_fu_2208_p1 = 23'd38;

assign mul_ln1118_94_fu_2215_p0 = sext_ln1118_95_fu_420_p1;

assign mul_ln1118_94_fu_2215_p1 = 24'd16777083;

assign mul_ln1118_95_fu_2222_p0 = sext_ln1118_97_fu_437_p1;

assign mul_ln1118_95_fu_2222_p1 = 24'd16777100;

assign mul_ln1118_96_fu_2229_p0 = sext_ln1118_98_fu_450_p1;

assign mul_ln1118_96_fu_2229_p1 = 24'd191;

assign mul_ln1118_97_fu_2236_p0 = sext_ln1118_99_fu_463_p1;

assign mul_ln1118_97_fu_2236_p1 = 24'd16777131;

assign mul_ln1118_98_fu_2243_p0 = sext_ln1118_fu_296_p1;

assign mul_ln1118_98_fu_2243_p1 = 24'd180;

assign mul_ln1118_99_fu_2250_p0 = sext_ln1118_83_fu_317_p1;

assign mul_ln1118_99_fu_2250_p1 = 24'd16777076;

assign mul_ln1118_fu_2117_p1 = 23'd53;

assign sext_ln1118_101_fu_480_p0 = data_9_V_read;

assign sext_ln1118_101_fu_480_p1 = sext_ln1118_101_fu_480_p0;

assign sext_ln1118_103_fu_650_p1 = $signed(shl_ln1118_s_fu_642_p3);

assign sext_ln1118_104_fu_767_p1 = $signed(shl_ln1118_33_fu_759_p3);

assign sext_ln1118_105_fu_779_p1 = $signed(shl_ln1118_34_fu_771_p3);

assign sext_ln1118_106_fu_913_p1 = $signed(shl_ln1118_35_fu_905_p3);

assign sext_ln1118_107_fu_925_p1 = $signed(shl_ln1118_36_fu_917_p3);

assign sext_ln1118_108_fu_992_p1 = shl_ln1118_38_fu_984_p3;

assign sext_ln1118_109_fu_1038_p1 = $signed(shl_ln1118_39_fu_1030_p3);

assign sext_ln1118_110_fu_1050_p1 = shl_ln1118_40_fu_1042_p3;

assign sext_ln1118_111_fu_1054_p1 = shl_ln1118_40_fu_1042_p3;

assign sext_ln1118_112_fu_1182_p1 = $signed(tmp_241_fu_1172_p4);

assign sext_ln1118_113_fu_1194_p1 = shl_ln1118_41_fu_1186_p3;

assign sext_ln1118_114_fu_1198_p1 = shl_ln1118_41_fu_1186_p3;

assign sext_ln1118_115_fu_1222_p1 = shl_ln1118_38_fu_984_p3;

assign sext_ln1118_116_fu_1272_p1 = $signed(shl_ln1118_42_fu_1264_p3);

assign sext_ln1118_117_fu_1290_p1 = $signed(shl_ln1118_43_fu_1282_p3);

assign sext_ln1118_118_fu_1322_p1 = $signed(shl_ln1118_44_fu_1314_p3);

assign sext_ln1118_119_fu_1334_p1 = $signed(shl_ln1118_45_fu_1326_p3);

assign sext_ln1118_120_fu_1420_p1 = $signed(trunc_ln708_145_fu_1410_p4);

assign sext_ln1118_121_fu_1458_p1 = $signed(shl_ln1118_46_fu_1450_p3);

assign sext_ln1118_122_fu_1772_p1 = $signed(shl_ln1118_47_fu_1764_p3);

assign sext_ln1118_123_fu_1784_p1 = $signed(shl_ln1118_48_fu_1776_p3);

assign sext_ln1118_124_fu_1812_p1 = $signed(shl_ln1118_49_fu_1804_p3);

assign sext_ln1118_125_fu_1824_p1 = $signed(shl_ln1118_50_fu_1816_p3);

assign sext_ln1118_126_fu_1856_p1 = $signed(shl_ln1118_51_fu_1848_p3);

assign sext_ln1118_127_fu_1218_p1 = $signed(tmp_242_fu_1208_p4);

assign sext_ln1118_128_fu_1844_p1 = $signed(tmp_243_fu_1834_p4);

assign sext_ln1118_129_fu_1876_p1 = $signed(tmp_244_fu_1866_p4);

assign sext_ln1118_83_fu_317_p0 = data_1_V_read;

assign sext_ln1118_83_fu_317_p1 = sext_ln1118_83_fu_317_p0;

assign sext_ln1118_85_fu_325_p0 = data_1_V_read;

assign sext_ln1118_85_fu_325_p1 = sext_ln1118_85_fu_325_p0;

assign sext_ln1118_86_fu_338_p0 = data_2_V_read;

assign sext_ln1118_86_fu_338_p1 = sext_ln1118_86_fu_338_p0;

assign sext_ln1118_88_fu_355_p0 = data_3_V_read;

assign sext_ln1118_88_fu_355_p1 = sext_ln1118_88_fu_355_p0;

assign sext_ln1118_90_fu_363_p0 = data_3_V_read;

assign sext_ln1118_91_fu_376_p0 = data_4_V_read;

assign sext_ln1118_91_fu_376_p1 = sext_ln1118_91_fu_376_p0;

assign sext_ln1118_92_fu_380_p0 = data_4_V_read;

assign sext_ln1118_92_fu_380_p1 = sext_ln1118_92_fu_380_p0;

assign sext_ln1118_93_fu_384_p0 = data_4_V_read;

assign sext_ln1118_93_fu_384_p1 = sext_ln1118_93_fu_384_p0;

assign sext_ln1118_94_fu_396_p1 = $signed(tmp_fu_388_p3);

assign sext_ln1118_95_fu_420_p0 = data_5_V_read;

assign sext_ln1118_95_fu_420_p1 = sext_ln1118_95_fu_420_p0;

assign sext_ln1118_96_fu_424_p0 = data_5_V_read;

assign sext_ln1118_96_fu_424_p1 = sext_ln1118_96_fu_424_p0;

assign sext_ln1118_97_fu_437_p1 = $signed(data_6_V_read);

assign sext_ln1118_98_fu_450_p1 = $signed(data_7_V_read);

assign sext_ln1118_99_fu_463_p0 = data_8_V_read;

assign sext_ln1118_99_fu_463_p1 = sext_ln1118_99_fu_463_p0;

assign sext_ln1118_fu_296_p0 = data_0_V_read;

assign sext_ln1118_fu_296_p1 = sext_ln1118_fu_296_p0;

assign sext_ln703_11_fu_1937_p1 = $signed(tmp_245_fu_1927_p4);

assign sext_ln703_12_fu_1953_p1 = $signed(add_ln703_251_fu_1947_p2);

assign sext_ln703_13_fu_1987_p1 = $signed(add_ln703_256_fu_1981_p2);

assign sext_ln703_fu_1370_p1 = $signed(add_ln703_221_fu_1364_p2);

assign sext_ln708_54_fu_416_p1 = $signed(trunc_ln708_101_fu_406_p4);

assign sext_ln708_55_fu_581_p1 = $signed(trunc_ln708_110_fu_572_p4);

assign sext_ln708_56_fu_594_p1 = $signed(trunc_ln708_111_fu_585_p4);

assign sext_ln708_57_fu_746_p1 = $signed(trunc_ln708_119_fu_736_p4);

assign sext_ln708_58_fu_799_p1 = $signed(trunc_ln708_121_fu_789_p4);

assign sext_ln708_59_fu_945_p1 = $signed(trunc_ln708_128_fu_935_p4);

assign sext_ln708_60_fu_1074_p1 = $signed(trunc_ln708_135_fu_1064_p4);

assign sext_ln708_61_fu_1153_p1 = $signed(trunc_ln708_138_fu_1144_p4);

assign sext_ln708_62_fu_1242_p1 = $signed(trunc_ln708_140_fu_1232_p4);

assign sext_ln708_63_fu_1310_p1 = $signed(trunc_ln708_143_fu_1300_p4);

assign sext_ln708_64_fu_1354_p1 = $signed(trunc_ln708_144_fu_1344_p4);

assign sext_ln708_65_fu_1433_p1 = $signed(trunc_ln708_146_fu_1424_p4);

assign sext_ln708_66_fu_1446_p1 = $signed(trunc_ln708_147_fu_1437_p4);

assign sext_ln708_67_fu_1478_p1 = $signed(trunc_ln708_148_fu_1468_p4);

assign sext_ln708_68_fu_1491_p1 = $signed(trunc_ln708_149_fu_1482_p4);

assign sext_ln708_69_fu_1504_p1 = $signed(trunc_ln708_150_fu_1495_p4);

assign sext_ln708_70_fu_1677_p1 = $signed(trunc_ln708_163_fu_1668_p4);

assign sext_ln708_71_fu_1690_p1 = $signed(trunc_ln708_164_fu_1681_p4);

assign sext_ln708_72_fu_1760_p1 = $signed(trunc_ln708_166_fu_1751_p4);

assign sext_ln708_73_fu_1923_p1 = $signed(trunc_ln708_171_fu_1913_p4);

assign sext_ln708_fu_313_p1 = $signed(trunc_ln_fu_304_p4);

assign shl_ln1118_33_fu_759_p1 = data_4_V_read;

assign shl_ln1118_33_fu_759_p3 = {{shl_ln1118_33_fu_759_p1}, {5'd0}};

assign shl_ln1118_34_fu_771_p1 = data_4_V_read;

assign shl_ln1118_34_fu_771_p3 = {{shl_ln1118_34_fu_771_p1}, {2'd0}};

assign shl_ln1118_35_fu_905_p1 = data_1_V_read;

assign shl_ln1118_35_fu_905_p3 = {{shl_ln1118_35_fu_905_p1}, {5'd0}};

assign shl_ln1118_36_fu_917_p1 = data_1_V_read;

assign shl_ln1118_36_fu_917_p3 = {{shl_ln1118_36_fu_917_p1}, {2'd0}};

assign shl_ln1118_37_fu_976_p1 = data_5_V_read;

assign shl_ln1118_37_fu_976_p3 = {{shl_ln1118_37_fu_976_p1}, {8'd0}};

assign shl_ln1118_38_fu_984_p1 = data_5_V_read;

assign shl_ln1118_38_fu_984_p3 = {{shl_ln1118_38_fu_984_p1}, {6'd0}};

assign shl_ln1118_39_fu_1030_p1 = data_8_V_read;

assign shl_ln1118_39_fu_1030_p3 = {{shl_ln1118_39_fu_1030_p1}, {6'd0}};

assign shl_ln1118_40_fu_1042_p1 = data_8_V_read;

assign shl_ln1118_40_fu_1042_p3 = {{shl_ln1118_40_fu_1042_p1}, {3'd0}};

assign shl_ln1118_41_fu_1186_p1 = data_4_V_read;

assign shl_ln1118_41_fu_1186_p3 = {{shl_ln1118_41_fu_1186_p1}, {1'd0}};

assign shl_ln1118_42_fu_1264_p1 = data_8_V_read;

assign shl_ln1118_42_fu_1264_p3 = {{shl_ln1118_42_fu_1264_p1}, {5'd0}};

assign shl_ln1118_43_fu_1282_p1 = data_8_V_read;

assign shl_ln1118_43_fu_1282_p3 = {{shl_ln1118_43_fu_1282_p1}, {2'd0}};

assign shl_ln1118_44_fu_1314_p1 = data_9_V_read;

assign shl_ln1118_44_fu_1314_p3 = {{shl_ln1118_44_fu_1314_p1}, {6'd0}};

assign shl_ln1118_45_fu_1326_p1 = data_9_V_read;

assign shl_ln1118_45_fu_1326_p3 = {{shl_ln1118_45_fu_1326_p1}, {3'd0}};

assign shl_ln1118_46_fu_1450_p1 = data_3_V_read;

assign shl_ln1118_46_fu_1450_p3 = {{shl_ln1118_46_fu_1450_p1}, {2'd0}};

assign shl_ln1118_47_fu_1764_p1 = data_2_V_read;

assign shl_ln1118_47_fu_1764_p3 = {{shl_ln1118_47_fu_1764_p1}, {7'd0}};

assign shl_ln1118_48_fu_1776_p1 = data_2_V_read;

assign shl_ln1118_48_fu_1776_p3 = {{shl_ln1118_48_fu_1776_p1}, {5'd0}};

assign shl_ln1118_49_fu_1804_p1 = data_3_V_read;

assign shl_ln1118_49_fu_1804_p3 = {{shl_ln1118_49_fu_1804_p1}, {5'd0}};

assign shl_ln1118_50_fu_1816_p1 = data_3_V_read;

assign shl_ln1118_50_fu_1816_p3 = {{shl_ln1118_50_fu_1816_p1}, {1'd0}};

assign shl_ln1118_51_fu_1848_p1 = data_4_V_read;

assign shl_ln1118_51_fu_1848_p3 = {{shl_ln1118_51_fu_1848_p1}, {3'd0}};

assign shl_ln1118_s_fu_642_p1 = data_9_V_read;

assign shl_ln1118_s_fu_642_p3 = {{shl_ln1118_s_fu_642_p1}, {1'd0}};

assign shl_ln_fu_634_p1 = data_9_V_read;

assign shl_ln_fu_634_p3 = {{shl_ln_fu_634_p1}, {8'd0}};

assign sub_ln1118_27_fu_400_p2 = ($signed(sext_ln1118_93_fu_384_p1) - $signed(sext_ln1118_94_fu_396_p1));

assign sub_ln1118_28_fu_996_p2 = ($signed(shl_ln1118_37_fu_976_p3) - $signed(sext_ln1118_108_fu_992_p1));

assign sub_ln1118_29_fu_1202_p2 = ($signed(sext_ln1118_114_fu_1198_p1) - $signed(sext_ln1118_94_fu_396_p1));

assign sub_ln1118_30_fu_1226_p2 = ($signed(sext_ln1118_96_fu_424_p1) - $signed(sext_ln1118_115_fu_1222_p1));

assign sub_ln1118_31_fu_1276_p2 = ($signed(22'd0) - $signed(sext_ln1118_116_fu_1272_p1));

assign sub_ln1118_32_fu_1294_p2 = ($signed(sub_ln1118_31_fu_1276_p2) - $signed(sext_ln1118_117_fu_1290_p1));

assign sub_ln1118_33_fu_1462_p2 = ($signed(19'd0) - $signed(sext_ln1118_121_fu_1458_p1));

assign sub_ln1118_34_fu_1788_p2 = ($signed(sext_ln1118_122_fu_1772_p1) - $signed(sext_ln1118_123_fu_1784_p1));

assign sub_ln1118_35_fu_1828_p2 = ($signed(sext_ln1118_124_fu_1812_p1) - $signed(sext_ln1118_125_fu_1824_p1));

assign sub_ln1118_36_fu_1860_p2 = ($signed(sext_ln1118_113_fu_1194_p1) - $signed(sext_ln1118_126_fu_1856_p1));

assign sub_ln1118_fu_929_p2 = ($signed(sext_ln1118_106_fu_913_p1) - $signed(sext_ln1118_107_fu_925_p1));

assign tmp_241_fu_1172_p4 = {{mul_ln1118_116_fu_1166_p2[20:8]}};

assign tmp_242_fu_1208_p4 = {{sub_ln1118_29_fu_1202_p2[20:8]}};

assign tmp_243_fu_1834_p4 = {{sub_ln1118_35_fu_1828_p2[21:8]}};

assign tmp_244_fu_1866_p4 = {{sub_ln1118_36_fu_1860_p2[19:8]}};

assign tmp_245_fu_1927_p1 = data_9_V_read;

assign tmp_245_fu_1927_p4 = {{tmp_245_fu_1927_p1[15:2]}};

assign tmp_fu_388_p1 = data_4_V_read;

assign tmp_fu_388_p3 = {{tmp_fu_388_p1}, {4'd0}};

assign trunc_ln708_100_fu_367_p4 = {{mul_ln1118_83_fu_2138_p2[23:8]}};

assign trunc_ln708_101_fu_406_p4 = {{sub_ln1118_27_fu_400_p2[20:8]}};

assign trunc_ln708_102_fu_428_p4 = {{mul_ln1118_84_fu_2145_p2[23:8]}};

assign trunc_ln708_103_fu_441_p4 = {{mul_ln1118_85_fu_2152_p2[23:8]}};

assign trunc_ln708_104_fu_454_p4 = {{mul_ln1118_86_fu_2159_p2[23:8]}};

assign trunc_ln708_105_fu_471_p4 = {{mul_ln1118_87_fu_2166_p2[23:8]}};

assign trunc_ln708_106_fu_488_p4 = {{mul_ln1118_88_fu_2173_p2[23:8]}};

assign trunc_ln708_107_fu_545_p4 = {{mul_ln1118_89_fu_2180_p2[23:8]}};

assign trunc_ln708_108_fu_554_p4 = {{mul_ln1118_90_fu_2187_p2[23:8]}};

assign trunc_ln708_109_fu_563_p4 = {{mul_ln1118_91_fu_2194_p2[23:8]}};

assign trunc_ln708_110_fu_572_p4 = {{mul_ln1118_92_fu_2201_p2[22:8]}};

assign trunc_ln708_111_fu_585_p4 = {{mul_ln1118_93_fu_2208_p2[22:8]}};

assign trunc_ln708_112_fu_598_p4 = {{mul_ln1118_94_fu_2215_p2[23:8]}};

assign trunc_ln708_113_fu_607_p4 = {{mul_ln1118_95_fu_2222_p2[23:8]}};

assign trunc_ln708_114_fu_616_p4 = {{mul_ln1118_96_fu_2229_p2[23:8]}};

assign trunc_ln708_115_fu_625_p4 = {{mul_ln1118_97_fu_2236_p2[23:8]}};

assign trunc_ln708_116_fu_660_p4 = {{add_ln1118_fu_654_p2[23:8]}};

assign trunc_ln708_117_fu_718_p4 = {{mul_ln1118_98_fu_2243_p2[23:8]}};

assign trunc_ln708_118_fu_727_p4 = {{mul_ln1118_99_fu_2250_p2[23:8]}};

assign trunc_ln708_119_fu_736_p1 = data_2_V_read;

assign trunc_ln708_119_fu_736_p4 = {{trunc_ln708_119_fu_736_p1[15:1]}};

assign trunc_ln708_120_fu_750_p4 = {{mul_ln1118_100_fu_2257_p2[23:8]}};

assign trunc_ln708_121_fu_789_p4 = {{add_ln1118_4_fu_783_p2[21:8]}};

assign trunc_ln708_122_fu_803_p4 = {{mul_ln1118_101_fu_2264_p2[23:8]}};

assign trunc_ln708_123_fu_812_p4 = {{mul_ln1118_102_fu_2271_p2[23:8]}};

assign trunc_ln708_124_fu_821_p4 = {{mul_ln1118_103_fu_2278_p2[23:8]}};

assign trunc_ln708_125_fu_830_p4 = {{mul_ln1118_104_fu_2285_p2[23:8]}};

assign trunc_ln708_126_fu_839_p4 = {{mul_ln1118_105_fu_2292_p2[23:8]}};

assign trunc_ln708_127_fu_896_p4 = {{mul_ln1118_106_fu_2299_p2[23:8]}};

assign trunc_ln708_128_fu_935_p4 = {{sub_ln1118_fu_929_p2[21:8]}};

assign trunc_ln708_129_fu_949_p4 = {{mul_ln1118_107_fu_2306_p2[23:8]}};

assign trunc_ln708_130_fu_958_p4 = {{mul_ln1118_108_fu_2313_p2[23:8]}};

assign trunc_ln708_131_fu_967_p4 = {{mul_ln1118_109_fu_2320_p2[23:8]}};

assign trunc_ln708_132_fu_1002_p4 = {{sub_ln1118_28_fu_996_p2[23:8]}};

assign trunc_ln708_133_fu_1012_p4 = {{mul_ln1118_110_fu_2327_p2[23:8]}};

assign trunc_ln708_134_fu_1021_p4 = {{mul_ln1118_111_fu_2334_p2[23:8]}};

assign trunc_ln708_135_fu_1064_p4 = {{add_ln1118_5_fu_1058_p2[22:8]}};

assign trunc_ln708_136_fu_1078_p4 = {{mul_ln1118_112_fu_2341_p2[23:8]}};

assign trunc_ln708_137_fu_1135_p4 = {{mul_ln1118_113_fu_2348_p2[23:8]}};

assign trunc_ln708_138_fu_1144_p4 = {{mul_ln1118_114_fu_2355_p2[22:8]}};

assign trunc_ln708_139_fu_1157_p4 = {{mul_ln1118_115_fu_2362_p2[23:8]}};

assign trunc_ln708_140_fu_1232_p4 = {{sub_ln1118_30_fu_1226_p2[22:8]}};

assign trunc_ln708_141_fu_1246_p4 = {{mul_ln1118_117_fu_2369_p2[23:8]}};

assign trunc_ln708_142_fu_1255_p4 = {{mul_ln1118_118_fu_2376_p2[23:8]}};

assign trunc_ln708_143_fu_1300_p4 = {{sub_ln1118_32_fu_1294_p2[21:8]}};

assign trunc_ln708_144_fu_1344_p4 = {{add_ln1118_6_fu_1338_p2[22:8]}};

assign trunc_ln708_145_fu_1410_p1 = data_0_V_read;

assign trunc_ln708_145_fu_1410_p4 = {{trunc_ln708_145_fu_1410_p1[15:8]}};

assign trunc_ln708_146_fu_1424_p4 = {{mul_ln1118_119_fu_2383_p2[21:8]}};

assign trunc_ln708_147_fu_1437_p4 = {{mul_ln1118_120_fu_2390_p2[22:8]}};

assign trunc_ln708_148_fu_1468_p4 = {{sub_ln1118_33_fu_1462_p2[18:8]}};

assign trunc_ln708_149_fu_1482_p4 = {{mul_ln1118_121_fu_2397_p2[22:8]}};

assign trunc_ln708_150_fu_1495_p4 = {{mul_ln1118_122_fu_2404_p2[22:8]}};

assign trunc_ln708_151_fu_1508_p4 = {{mul_ln1118_123_fu_2411_p2[23:8]}};

assign trunc_ln708_152_fu_1517_p4 = {{mul_ln1118_124_fu_2418_p2[23:8]}};

assign trunc_ln708_153_fu_1526_p4 = {{mul_ln1118_125_fu_2425_p2[23:8]}};

assign trunc_ln708_154_fu_1535_p4 = {{mul_ln1118_126_fu_2432_p2[23:8]}};

assign trunc_ln708_155_fu_1596_p4 = {{mul_ln1118_127_fu_2439_p2[23:8]}};

assign trunc_ln708_156_fu_1605_p4 = {{mul_ln1118_128_fu_2446_p2[23:8]}};

assign trunc_ln708_157_fu_1614_p4 = {{mul_ln1118_129_fu_2453_p2[23:8]}};

assign trunc_ln708_158_fu_1623_p4 = {{mul_ln1118_130_fu_2460_p2[23:8]}};

assign trunc_ln708_159_fu_1632_p4 = {{mul_ln1118_131_fu_2467_p2[23:8]}};

assign trunc_ln708_160_fu_1641_p4 = {{mul_ln1118_132_fu_2474_p2[23:8]}};

assign trunc_ln708_161_fu_1650_p4 = {{mul_ln1118_133_fu_2481_p2[23:8]}};

assign trunc_ln708_162_fu_1659_p4 = {{mul_ln1118_134_fu_2488_p2[23:8]}};

assign trunc_ln708_163_fu_1668_p4 = {{mul_ln1118_135_fu_2495_p2[22:8]}};

assign trunc_ln708_164_fu_1681_p4 = {{mul_ln1118_136_fu_2502_p2[22:8]}};

assign trunc_ln708_165_fu_1742_p4 = {{mul_ln1118_137_fu_2509_p2[23:8]}};

assign trunc_ln708_166_fu_1751_p4 = {{mul_ln1118_138_fu_2516_p2[22:8]}};

assign trunc_ln708_167_fu_1794_p4 = {{sub_ln1118_34_fu_1788_p2[23:8]}};

assign trunc_ln708_168_fu_1880_p4 = {{mul_ln1118_139_fu_2523_p2[23:8]}};

assign trunc_ln708_169_fu_1889_p4 = {{mul_ln1118_140_fu_2530_p2[23:8]}};

assign trunc_ln708_170_fu_1898_p4 = {{mul_ln1118_141_fu_2537_p2[23:8]}};

assign trunc_ln708_171_fu_1913_p4 = {{add_ln1118_7_fu_1907_p2[21:8]}};

assign trunc_ln708_99_fu_346_p4 = {{mul_ln1118_82_fu_2131_p2[23:8]}};

assign trunc_ln708_s_fu_329_p4 = {{mul_ln1118_81_fu_2124_p2[23:8]}};

assign trunc_ln_fu_304_p4 = {{mul_ln1118_fu_2117_p2[22:8]}};

assign zext_ln703_fu_1586_p1 = add_ln703_236_fu_1580_p2;

endmodule //dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3
