// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_mult_3lyr_ap_fixed_ap_fixed_16_8_5_3_0_config7_s (
        ap_clk,
        ap_rst,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_V_read;
input  [15:0] data_1_V_read;
input  [15:0] data_2_V_read;
input  [15:0] data_3_V_read;
input  [15:0] data_4_V_read;
input  [15:0] data_5_V_read;
input  [15:0] data_6_V_read;
input  [15:0] data_7_V_read;
input  [15:0] data_8_V_read;
input  [15:0] data_9_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;

reg   [15:0] data0_logits_0_V_reg_292;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] data0_logits_1_V_reg_297;
reg   [15:0] data0_logits_2_V_reg_302;
reg   [15:0] data0_logits_3_V_reg_307;
reg   [15:0] data0_logits_4_V_reg_312;
reg   [15:0] data0_logits_5_V_reg_317;
reg   [15:0] data0_logits_6_V_reg_322;
reg   [15:0] data0_logits_7_V_reg_327;
reg   [15:0] data0_0_V_reg_332;
reg   [15:0] data0_1_V_reg_337;
reg   [15:0] data0_2_V_reg_342;
reg   [15:0] data0_3_V_reg_347;
reg   [15:0] data0_4_V_reg_352;
reg   [15:0] data0_5_V_reg_357;
reg   [15:0] data0_6_V_reg_362;
reg   [15:0] data0_7_V_reg_367;
reg   [15:0] data1_logits_0_V_reg_372;
reg   [15:0] data1_logits_1_V_reg_377;
reg   [15:0] data1_logits_2_V_reg_382;
reg   [15:0] data1_logits_3_V_reg_387;
reg   [15:0] data1_logits_4_V_reg_392;
reg   [15:0] data1_logits_5_V_reg_397;
reg   [15:0] data1_logits_6_V_reg_402;
reg   [15:0] data1_logits_7_V_reg_407;
reg   [15:0] data1_0_V_reg_412;
reg   [15:0] data1_1_V_reg_417;
reg   [15:0] data1_2_V_reg_422;
reg   [15:0] data1_3_V_reg_427;
reg   [15:0] data1_4_V_reg_432;
reg   [15:0] data1_5_V_reg_437;
reg   [15:0] data1_6_V_reg_442;
reg   [15:0] data1_7_V_reg_447;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_0;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_1;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_2;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_3;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_4;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_5;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_6;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_7;
reg    grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call10;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call10;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call10;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call10;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call10;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call10;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call10;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call10;
wire    ap_block_pp0_stage0_11001_ignoreCallOp19;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_0;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_1;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_2;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_3;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_4;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_5;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_6;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_7;
reg    grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call28;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call28;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call28;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call28;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call28;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call28;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call28;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call28;
wire    ap_block_pp0_stage0_11001_ignoreCallOp38;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_0;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_1;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_2;
wire   [15:0] grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_3;
reg    grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call46;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call46;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call46;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call46;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call46;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call46;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call46;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call46;
wire    ap_block_pp0_stage0_11001_ignoreCallOp57;
wire    call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_ready;
wire   [15:0] call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_0;
wire   [15:0] call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_1;
wire   [15:0] call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_2;
wire   [15:0] call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_3;
wire   [15:0] call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_4;
wire   [15:0] call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_5;
wire   [15:0] call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_6;
wire   [15:0] call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_7;
wire    call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_ready;
wire   [15:0] call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_0;
wire   [15:0] call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_1;
wire   [15:0] call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_2;
wire   [15:0] call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_3;
wire   [15:0] call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_4;
wire   [15:0] call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_5;
wire   [15:0] call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_6;
wire   [15:0] call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_7;
wire    ap_block_pp0_stage0;
reg   [15:0] data_0_V_read_int_reg;
reg   [15:0] data_1_V_read_int_reg;
reg   [15:0] data_2_V_read_int_reg;
reg   [15:0] data_3_V_read_int_reg;
reg   [15:0] data_4_V_read_int_reg;
reg   [15:0] data_5_V_read_int_reg;
reg   [15:0] data_6_V_read_int_reg;
reg   [15:0] data_7_V_read_int_reg;
reg   [15:0] data_8_V_read_int_reg;
reg   [15:0] data_9_V_read_int_reg;

dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1 grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_V_read(data_0_V_read_int_reg),
    .data_1_V_read(data_1_V_read_int_reg),
    .data_2_V_read(data_2_V_read_int_reg),
    .data_3_V_read(data_3_V_read_int_reg),
    .data_4_V_read(data_4_V_read_int_reg),
    .data_5_V_read(data_5_V_read_int_reg),
    .data_6_V_read(data_6_V_read_int_reg),
    .data_7_V_read(data_7_V_read_int_reg),
    .data_8_V_read(data_8_V_read_int_reg),
    .data_9_V_read(data_9_V_read_int_reg),
    .ap_return_0(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_0),
    .ap_return_1(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_1),
    .ap_return_2(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_2),
    .ap_return_3(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_3),
    .ap_return_4(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_4),
    .ap_return_5(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_5),
    .ap_return_6(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_6),
    .ap_return_7(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_7),
    .ap_ce(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_ce)
);

dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0 grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_V_read(data0_0_V_reg_332),
    .data_1_V_read(data0_1_V_reg_337),
    .data_2_V_read(data0_2_V_reg_342),
    .data_3_V_read(data0_3_V_reg_347),
    .data_4_V_read(data0_4_V_reg_352),
    .data_5_V_read(data0_5_V_reg_357),
    .data_6_V_read(data0_6_V_reg_362),
    .data_7_V_read(data0_7_V_reg_367),
    .ap_return_0(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_0),
    .ap_return_1(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_1),
    .ap_return_2(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_2),
    .ap_return_3(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_3),
    .ap_return_4(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_4),
    .ap_return_5(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_5),
    .ap_return_6(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_6),
    .ap_return_7(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_7),
    .ap_ce(grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_ce)
);

dense_resource_rf_leq_nin_0_0_0_0_0 grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_V_read(data1_0_V_reg_412),
    .data_1_V_read(data1_1_V_reg_417),
    .data_2_V_read(data1_2_V_reg_422),
    .data_3_V_read(data1_3_V_reg_427),
    .data_4_V_read(data1_4_V_reg_432),
    .data_5_V_read(data1_5_V_reg_437),
    .data_6_V_read(data1_6_V_reg_442),
    .data_7_V_read(data1_7_V_reg_447),
    .ap_return_0(grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_0),
    .ap_return_1(grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_1),
    .ap_return_2(grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_2),
    .ap_return_3(grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_3),
    .ap_ce(grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_ce)
);

relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140(
    .ap_ready(call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_ready),
    .data_0_V_read(data0_logits_0_V_reg_292),
    .data_1_V_read(data0_logits_1_V_reg_297),
    .data_2_V_read(data0_logits_2_V_reg_302),
    .data_3_V_read(data0_logits_3_V_reg_307),
    .data_4_V_read(data0_logits_4_V_reg_312),
    .data_5_V_read(data0_logits_5_V_reg_317),
    .data_6_V_read(data0_logits_6_V_reg_322),
    .data_7_V_read(data0_logits_7_V_reg_327),
    .ap_return_0(call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_0),
    .ap_return_1(call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_1),
    .ap_return_2(call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_2),
    .ap_return_3(call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_3),
    .ap_return_4(call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_4),
    .ap_return_5(call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_5),
    .ap_return_6(call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_6),
    .ap_return_7(call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_7)
);

relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152(
    .ap_ready(call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_ready),
    .data_0_V_read(data1_logits_0_V_reg_372),
    .data_1_V_read(data1_logits_1_V_reg_377),
    .data_2_V_read(data1_logits_2_V_reg_382),
    .data_3_V_read(data1_logits_3_V_reg_387),
    .data_4_V_read(data1_logits_4_V_reg_392),
    .data_5_V_read(data1_logits_5_V_reg_397),
    .data_6_V_read(data1_logits_6_V_reg_402),
    .data_7_V_read(data1_logits_7_V_reg_407),
    .ap_return_0(call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_0),
    .ap_return_1(call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_1),
    .ap_return_2(call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_2),
    .ap_return_3(call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_3),
    .ap_return_4(call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_4),
    .ap_return_5(call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_5),
    .ap_return_6(call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_6),
    .ap_return_7(call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_7)
);

always @ (posedge ap_clk) begin
    data_0_V_read_int_reg <= data_0_V_read;
end

always @ (posedge ap_clk) begin
    data_1_V_read_int_reg <= data_1_V_read;
end

always @ (posedge ap_clk) begin
    data_2_V_read_int_reg <= data_2_V_read;
end

always @ (posedge ap_clk) begin
    data_3_V_read_int_reg <= data_3_V_read;
end

always @ (posedge ap_clk) begin
    data_4_V_read_int_reg <= data_4_V_read;
end

always @ (posedge ap_clk) begin
    data_5_V_read_int_reg <= data_5_V_read;
end

always @ (posedge ap_clk) begin
    data_6_V_read_int_reg <= data_6_V_read;
end

always @ (posedge ap_clk) begin
    data_7_V_read_int_reg <= data_7_V_read;
end

always @ (posedge ap_clk) begin
    data_8_V_read_int_reg <= data_8_V_read;
end

always @ (posedge ap_clk) begin
    data_9_V_read_int_reg <= data_9_V_read;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        data0_0_V_reg_332 <= call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_0;
        data0_1_V_reg_337 <= call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_1;
        data0_2_V_reg_342 <= call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_2;
        data0_3_V_reg_347 <= call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_3;
        data0_4_V_reg_352 <= call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_4;
        data0_5_V_reg_357 <= call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_5;
        data0_6_V_reg_362 <= call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_6;
        data0_7_V_reg_367 <= call_ret47_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_s_fu_140_ap_return_7;
        data0_logits_0_V_reg_292 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_0;
        data0_logits_1_V_reg_297 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_1;
        data0_logits_2_V_reg_302 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_2;
        data0_logits_3_V_reg_307 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_3;
        data0_logits_4_V_reg_312 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_4;
        data0_logits_5_V_reg_317 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_5;
        data0_logits_6_V_reg_322 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_6;
        data0_logits_7_V_reg_327 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_return_7;
        data1_0_V_reg_412 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_0;
        data1_1_V_reg_417 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_1;
        data1_2_V_reg_422 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_2;
        data1_3_V_reg_427 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_3;
        data1_4_V_reg_432 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_4;
        data1_5_V_reg_437 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_5;
        data1_6_V_reg_442 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_6;
        data1_7_V_reg_447 <= call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_s_fu_152_ap_return_7;
        data1_logits_0_V_reg_372 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_0;
        data1_logits_1_V_reg_377 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_1;
        data1_logits_2_V_reg_382 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_2;
        data1_logits_3_V_reg_387 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_3;
        data1_logits_4_V_reg_392 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_4;
        data1_logits_5_V_reg_397 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_5;
        data1_logits_6_V_reg_402 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_6;
        data1_logits_7_V_reg_407 <= grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_return_7;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp19)) begin
        grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_ce = 1'b1;
    end else begin
        grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_1_fu_92_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp38)) begin
        grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_ce = 1'b1;
    end else begin
        grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_fu_116_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp57)) begin
        grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_ce = 1'b1;
    end else begin
        grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp19 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp38 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp57 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call46 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call46 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call46 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call46 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call46 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call46 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call46 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call46 = ~(1'b1 == 1'b1);

assign ap_return_0 = grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_0;

assign ap_return_1 = grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_1;

assign ap_return_2 = grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_2;

assign ap_return_3 = grp_dense_resource_rf_leq_nin_0_0_0_0_0_fu_128_ap_return_3;

endmodule //dense_mult_3lyr_ap_fixed_ap_fixed_16_8_5_3_0_config7_s
