// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::ap_const_logic_1 = sc_dt::Log_1;
const bool concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::ap_const_boolean_1 = true;
const sc_logic concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::ap_const_logic_0 = sc_dt::Log_0;

concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( data1_0_V_read );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( data1_1_V_read );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( data1_2_V_read );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( data2_0_V_read );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( data2_1_V_read );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( data2_2_V_read );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( data2_3_V_read );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data1_0_V_read, "(port)data1_0_V_read");
    sc_trace(mVcdFile, data1_1_V_read, "(port)data1_1_V_read");
    sc_trace(mVcdFile, data1_2_V_read, "(port)data1_2_V_read");
    sc_trace(mVcdFile, data2_0_V_read, "(port)data2_0_V_read");
    sc_trace(mVcdFile, data2_1_V_read, "(port)data2_1_V_read");
    sc_trace(mVcdFile, data2_2_V_read, "(port)data2_2_V_read");
    sc_trace(mVcdFile, data2_3_V_read, "(port)data2_3_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
#endif

    }
}

concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::~concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::thread_ap_return_0() {
    ap_return_0 = data1_0_V_read.read();
}

void concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::thread_ap_return_1() {
    ap_return_1 = data1_1_V_read.read();
}

void concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::thread_ap_return_2() {
    ap_return_2 = data1_2_V_read.read();
}

void concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::thread_ap_return_3() {
    ap_return_3 = data2_0_V_read.read();
}

void concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::thread_ap_return_4() {
    ap_return_4 = data2_1_V_read.read();
}

void concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::thread_ap_return_5() {
    ap_return_5 = data2_2_V_read.read();
}

void concatenate1d_ap_fixed_ap_fixed_ap_fixed_merge_config1_s::thread_ap_return_6() {
    ap_return_6 = data2_3_V_read.read();
}

}

