// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_mult_3lyr_ap_fixed_ap_fixed_config11_s_HH_
#define _dense_mult_3lyr_ap_fixed_ap_fixed_config11_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3.h"
#include "dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2.h"
#include "relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1.h"
#include "relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1.h"
#include "myproject_mul_mul_16s_7ns_23_1_0.h"
#include "myproject_mul_mul_16s_8s_24_1_0.h"
#include "myproject_mul_mul_16s_9s_24_1_0.h"
#include "myproject_mul_mul_16s_8ns_24_1_0.h"
#include "myproject_mul_mul_16s_6s_22_1_0.h"
#include "myproject_mul_mul_16s_6ns_22_1_0.h"

namespace ap_rtl {

struct dense_mult_3lyr_ap_fixed_ap_fixed_config11_s : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<16> > data_0_V_read;
    sc_in< sc_lv<16> > data_1_V_read;
    sc_in< sc_lv<16> > data_2_V_read;
    sc_in< sc_lv<16> > data_3_V_read;
    sc_in< sc_lv<16> > data_4_V_read;
    sc_in< sc_lv<16> > data_5_V_read;
    sc_in< sc_lv<16> > data_6_V_read;
    sc_in< sc_lv<16> > data_7_V_read;
    sc_in< sc_lv<16> > data_8_V_read;
    sc_in< sc_lv<16> > data_9_V_read;
    sc_out< sc_lv<16> > ap_return;


    // Module declarations
    dense_mult_3lyr_ap_fixed_ap_fixed_config11_s(sc_module_name name);
    SC_HAS_PROCESS(dense_mult_3lyr_ap_fixed_ap_fixed_config11_s);

    ~dense_mult_3lyr_ap_fixed_ap_fixed_config11_s();

    sc_trace_file* mVcdFile;

    dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3* grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3_fu_130;
    dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2* grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2_fu_154;
    relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1* call_ret48_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1_fu_166;
    relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1* call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1_fu_178;
    myproject_mul_mul_16s_7ns_23_1_0<1,1,16,7,23>* myproject_mul_mul_16s_7ns_23_1_0_U1921;
    myproject_mul_mul_16s_8s_24_1_0<1,1,16,8,24>* myproject_mul_mul_16s_8s_24_1_0_U1922;
    myproject_mul_mul_16s_9s_24_1_0<1,1,16,9,24>* myproject_mul_mul_16s_9s_24_1_0_U1923;
    myproject_mul_mul_16s_8ns_24_1_0<1,1,16,8,24>* myproject_mul_mul_16s_8ns_24_1_0_U1924;
    myproject_mul_mul_16s_8s_24_1_0<1,1,16,8,24>* myproject_mul_mul_16s_8s_24_1_0_U1925;
    myproject_mul_mul_16s_6s_22_1_0<1,1,16,6,22>* myproject_mul_mul_16s_6s_22_1_0_U1926;
    myproject_mul_mul_16s_6ns_22_1_0<1,1,16,6,22>* myproject_mul_mul_16s_6ns_22_1_0_U1927;
    sc_signal< sc_lv<16> > data0_0_V_reg_565;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<16> > data0_1_V_reg_570;
    sc_signal< sc_lv<16> > data0_2_V_reg_575;
    sc_signal< sc_lv<16> > data0_3_V_reg_580;
    sc_signal< sc_lv<16> > data0_4_V_reg_585;
    sc_signal< sc_lv<16> > data0_5_V_reg_590;
    sc_signal< sc_lv<16> > data0_6_V_reg_595;
    sc_signal< sc_lv<16> > data0_7_V_reg_600;
    sc_signal< sc_lv<16> > data1_logits_0_V_reg_605;
    sc_signal< sc_lv<16> > data1_logits_1_V_reg_610;
    sc_signal< sc_lv<16> > data1_logits_2_V_reg_615;
    sc_signal< sc_lv<16> > data1_logits_3_V_reg_620;
    sc_signal< sc_lv<16> > data1_logits_4_V_reg_625;
    sc_signal< sc_lv<16> > data1_logits_5_V_reg_630;
    sc_signal< sc_lv<16> > data1_logits_6_V_reg_635;
    sc_signal< sc_lv<16> > data1_logits_7_V_reg_640;
    sc_signal< sc_lv<16> > data1_4_V_reg_645;
    sc_signal< sc_lv<16> > trunc_ln708_230_reg_651;
    sc_signal< sc_lv<14> > trunc_ln708_231_reg_656;
    sc_signal< sc_lv<14> > tmp_reg_661;
    sc_signal< sc_lv<16> > add_ln703_fu_421_p2;
    sc_signal< sc_lv<16> > add_ln703_reg_666;
    sc_signal< sc_lv<16> > add_ln703_322_fu_427_p2;
    sc_signal< sc_lv<16> > add_ln703_322_reg_671;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3_fu_130_ap_return_0;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3_fu_130_ap_return_1;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3_fu_130_ap_return_2;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3_fu_130_ap_return_3;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3_fu_130_ap_return_4;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3_fu_130_ap_return_5;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3_fu_130_ap_return_6;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3_fu_130_ap_return_7;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3_fu_130_ap_ce;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0_ignore_call10;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1_ignore_call10;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2_ignore_call10;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3_ignore_call10;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4_ignore_call10;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5_ignore_call10;
    sc_signal< bool > ap_block_pp0_stage0_11001_ignoreCallOp17;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2_fu_154_ap_return_0;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2_fu_154_ap_return_1;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2_fu_154_ap_return_2;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2_fu_154_ap_return_3;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2_fu_154_ap_return_4;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2_fu_154_ap_return_5;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2_fu_154_ap_return_6;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2_fu_154_ap_return_7;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2_fu_154_ap_ce;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0_ignore_call28;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1_ignore_call28;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2_ignore_call28;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3_ignore_call28;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4_ignore_call28;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5_ignore_call28;
    sc_signal< bool > ap_block_pp0_stage0_11001_ignoreCallOp36;
    sc_signal< sc_logic > call_ret48_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1_fu_166_ap_ready;
    sc_signal< sc_lv<16> > call_ret48_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1_fu_166_ap_return_0;
    sc_signal< sc_lv<16> > call_ret48_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1_fu_166_ap_return_1;
    sc_signal< sc_lv<16> > call_ret48_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1_fu_166_ap_return_2;
    sc_signal< sc_lv<16> > call_ret48_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1_fu_166_ap_return_3;
    sc_signal< sc_lv<16> > call_ret48_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1_fu_166_ap_return_4;
    sc_signal< sc_lv<16> > call_ret48_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1_fu_166_ap_return_5;
    sc_signal< sc_lv<16> > call_ret48_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1_fu_166_ap_return_6;
    sc_signal< sc_lv<16> > call_ret48_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config1_1_fu_166_ap_return_7;
    sc_signal< sc_logic > call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1_fu_178_ap_ready;
    sc_signal< sc_lv<16> > call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1_fu_178_ap_return_0;
    sc_signal< sc_lv<16> > call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1_fu_178_ap_return_1;
    sc_signal< sc_lv<16> > call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1_fu_178_ap_return_2;
    sc_signal< sc_lv<16> > call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1_fu_178_ap_return_3;
    sc_signal< sc_lv<16> > call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1_fu_178_ap_return_4;
    sc_signal< sc_lv<16> > call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1_fu_178_ap_return_5;
    sc_signal< sc_lv<16> > call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1_fu_178_ap_return_6;
    sc_signal< sc_lv<16> > call_ret_relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config2_1_fu_178_ap_return_7;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<23> > mul_ln1118_fu_516_p2;
    sc_signal< sc_lv<15> > trunc_ln_fu_330_p4;
    sc_signal< sc_lv<24> > mul_ln1118_162_fu_523_p2;
    sc_signal< sc_lv<24> > mul_ln1118_163_fu_530_p2;
    sc_signal< sc_lv<24> > mul_ln1118_164_fu_537_p2;
    sc_signal< sc_lv<24> > mul_ln1118_165_fu_544_p2;
    sc_signal< sc_lv<22> > mul_ln1118_166_fu_551_p2;
    sc_signal< sc_lv<22> > mul_ln1118_167_fu_558_p2;
    sc_signal< sc_lv<16> > sext_ln708_fu_339_p1;
    sc_signal< sc_lv<16> > trunc_ln708_s_fu_347_p4;
    sc_signal< sc_lv<16> > trunc_ln708_227_fu_360_p4;
    sc_signal< sc_lv<16> > trunc_ln708_228_fu_373_p4;
    sc_signal< sc_lv<24> > shl_ln_fu_433_p3;
    sc_signal< sc_lv<17> > shl_ln1118_s_fu_446_p3;
    sc_signal< sc_lv<24> > sub_ln1118_fu_440_p2;
    sc_signal< sc_lv<24> > sext_ln1118_168_fu_453_p1;
    sc_signal< sc_lv<24> > sub_ln1118_54_fu_457_p2;
    sc_signal< sc_lv<16> > trunc_ln708_229_fu_463_p4;
    sc_signal< sc_lv<15> > sext_ln703_fu_476_p1;
    sc_signal< sc_lv<15> > add_ln703_325_fu_488_p2;
    sc_signal< sc_lv<16> > sext_ln703_30_fu_494_p1;
    sc_signal< sc_lv<16> > sext_ln708_98_fu_473_p1;
    sc_signal< sc_lv<16> > add_ln703_326_fu_498_p2;
    sc_signal< sc_lv<16> > add_ln703_324_fu_483_p2;
    sc_signal< sc_lv<16> > add_ln703_327_fu_504_p2;
    sc_signal< sc_lv<16> > add_ln703_323_fu_479_p2;
    sc_signal< sc_lv<7> > mul_ln1118_fu_516_p1;
    sc_signal< sc_lv<8> > mul_ln1118_162_fu_523_p1;
    sc_signal< sc_lv<9> > mul_ln1118_163_fu_530_p1;
    sc_signal< sc_lv<8> > mul_ln1118_164_fu_537_p1;
    sc_signal< sc_lv<8> > mul_ln1118_165_fu_544_p1;
    sc_signal< sc_lv<6> > mul_ln1118_166_fu_551_p1;
    sc_signal< sc_lv<6> > mul_ln1118_167_fu_558_p1;
    sc_signal< sc_lv<16> > data_0_V_read_int_reg;
    sc_signal< sc_lv<16> > data_1_V_read_int_reg;
    sc_signal< sc_lv<16> > data_2_V_read_int_reg;
    sc_signal< sc_lv<16> > data_3_V_read_int_reg;
    sc_signal< sc_lv<16> > data_4_V_read_int_reg;
    sc_signal< sc_lv<16> > data_5_V_read_int_reg;
    sc_signal< sc_lv<16> > data_6_V_read_int_reg;
    sc_signal< sc_lv<16> > data_7_V_read_int_reg;
    sc_signal< sc_lv<16> > data_8_V_read_int_reg;
    sc_signal< sc_lv<16> > data_9_V_read_int_reg;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<24> ap_const_lv24_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<15> ap_const_lv15_7FC3;
    static const sc_lv<23> ap_const_lv23_34;
    static const sc_lv<24> ap_const_lv24_FFFF94;
    static const sc_lv<24> ap_const_lv24_FFFF3B;
    static const sc_lv<24> ap_const_lv24_73;
    static const sc_lv<24> ap_const_lv24_FFFF96;
    static const sc_lv<22> ap_const_lv22_3FFFE6;
    static const sc_lv<22> ap_const_lv22_13;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln703_322_fu_427_p2();
    void thread_add_ln703_323_fu_479_p2();
    void thread_add_ln703_324_fu_483_p2();
    void thread_add_ln703_325_fu_488_p2();
    void thread_add_ln703_326_fu_498_p2();
    void thread_add_ln703_327_fu_504_p2();
    void thread_add_ln703_fu_421_p2();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_11001_ignoreCallOp17();
    void thread_ap_block_pp0_stage0_11001_ignoreCallOp36();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state1_pp0_stage0_iter0_ignore_call10();
    void thread_ap_block_state1_pp0_stage0_iter0_ignore_call28();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_block_state2_pp0_stage0_iter1_ignore_call10();
    void thread_ap_block_state2_pp0_stage0_iter1_ignore_call28();
    void thread_ap_block_state3_pp0_stage0_iter2();
    void thread_ap_block_state3_pp0_stage0_iter2_ignore_call10();
    void thread_ap_block_state3_pp0_stage0_iter2_ignore_call28();
    void thread_ap_block_state4_pp0_stage0_iter3();
    void thread_ap_block_state4_pp0_stage0_iter3_ignore_call10();
    void thread_ap_block_state4_pp0_stage0_iter3_ignore_call28();
    void thread_ap_block_state5_pp0_stage0_iter4();
    void thread_ap_block_state5_pp0_stage0_iter4_ignore_call10();
    void thread_ap_block_state5_pp0_stage0_iter4_ignore_call28();
    void thread_ap_block_state6_pp0_stage0_iter5();
    void thread_ap_block_state6_pp0_stage0_iter5_ignore_call10();
    void thread_ap_block_state6_pp0_stage0_iter5_ignore_call28();
    void thread_ap_return();
    void thread_grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_2_fu_154_ap_ce();
    void thread_grp_dense_resource_rf_leq_nin_0_0_0_0_0_0_0_0_0_3_fu_130_ap_ce();
    void thread_mul_ln1118_162_fu_523_p1();
    void thread_mul_ln1118_163_fu_530_p1();
    void thread_mul_ln1118_164_fu_537_p1();
    void thread_mul_ln1118_165_fu_544_p1();
    void thread_mul_ln1118_166_fu_551_p1();
    void thread_mul_ln1118_167_fu_558_p1();
    void thread_mul_ln1118_fu_516_p1();
    void thread_sext_ln1118_168_fu_453_p1();
    void thread_sext_ln703_30_fu_494_p1();
    void thread_sext_ln703_fu_476_p1();
    void thread_sext_ln708_98_fu_473_p1();
    void thread_sext_ln708_fu_339_p1();
    void thread_shl_ln1118_s_fu_446_p3();
    void thread_shl_ln_fu_433_p3();
    void thread_sub_ln1118_54_fu_457_p2();
    void thread_sub_ln1118_fu_440_p2();
    void thread_trunc_ln708_227_fu_360_p4();
    void thread_trunc_ln708_228_fu_373_p4();
    void thread_trunc_ln708_229_fu_463_p4();
    void thread_trunc_ln708_s_fu_347_p4();
    void thread_trunc_ln_fu_330_p4();
};

}

using namespace ap_rtl;

#endif
