// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module reduce_ap_fixed_16_Op_add_ap_fixed_16_8_5_3_0_s (
        ap_ready,
        x_0_V_read,
        x_1_V_read,
        x_2_V_read,
        x_3_V_read,
        x_4_V_read,
        x_5_V_read,
        x_6_V_read,
        x_7_V_read,
        x_8_V_read,
        x_9_V_read,
        x_10_V_read,
        x_11_V_read,
        x_12_V_read,
        x_13_V_read,
        x_14_V_read,
        x_15_V_read,
        ap_return
);


output   ap_ready;
input  [15:0] x_0_V_read;
input  [15:0] x_1_V_read;
input  [15:0] x_2_V_read;
input  [15:0] x_3_V_read;
input  [15:0] x_4_V_read;
input  [15:0] x_5_V_read;
input  [15:0] x_6_V_read;
input  [15:0] x_7_V_read;
input  [15:0] x_8_V_read;
input  [15:0] x_9_V_read;
input  [15:0] x_10_V_read;
input  [15:0] x_11_V_read;
input  [15:0] x_12_V_read;
input  [15:0] x_13_V_read;
input  [15:0] x_14_V_read;
input  [15:0] x_15_V_read;
output  [15:0] ap_return;

wire   [15:0] add_ln703_2_fu_136_p2;
wire   [15:0] add_ln703_1_fu_130_p2;
wire   [15:0] add_ln703_5_fu_154_p2;
wire   [15:0] add_ln703_4_fu_148_p2;
wire   [15:0] add_ln703_6_fu_160_p2;
wire   [15:0] add_ln703_3_fu_142_p2;
wire   [15:0] add_ln703_9_fu_178_p2;
wire   [15:0] add_ln703_8_fu_172_p2;
wire   [15:0] add_ln703_12_fu_196_p2;
wire   [15:0] add_ln703_11_fu_190_p2;
wire   [15:0] add_ln703_13_fu_202_p2;
wire   [15:0] add_ln703_10_fu_184_p2;
wire   [15:0] add_ln703_14_fu_208_p2;
wire   [15:0] add_ln703_7_fu_166_p2;

assign add_ln703_10_fu_184_p2 = (add_ln703_9_fu_178_p2 + add_ln703_8_fu_172_p2);

assign add_ln703_11_fu_190_p2 = (x_4_V_read + x_5_V_read);

assign add_ln703_12_fu_196_p2 = (x_6_V_read + x_7_V_read);

assign add_ln703_13_fu_202_p2 = (add_ln703_12_fu_196_p2 + add_ln703_11_fu_190_p2);

assign add_ln703_14_fu_208_p2 = (add_ln703_13_fu_202_p2 + add_ln703_10_fu_184_p2);

assign add_ln703_1_fu_130_p2 = (x_15_V_read + x_14_V_read);

assign add_ln703_2_fu_136_p2 = (x_12_V_read + x_13_V_read);

assign add_ln703_3_fu_142_p2 = (add_ln703_2_fu_136_p2 + add_ln703_1_fu_130_p2);

assign add_ln703_4_fu_148_p2 = (x_8_V_read + x_9_V_read);

assign add_ln703_5_fu_154_p2 = (x_10_V_read + x_11_V_read);

assign add_ln703_6_fu_160_p2 = (add_ln703_5_fu_154_p2 + add_ln703_4_fu_148_p2);

assign add_ln703_7_fu_166_p2 = (add_ln703_6_fu_160_p2 + add_ln703_3_fu_142_p2);

assign add_ln703_8_fu_172_p2 = (x_0_V_read + x_1_V_read);

assign add_ln703_9_fu_178_p2 = (x_2_V_read + x_3_V_read);

assign ap_ready = 1'b1;

assign ap_return = (add_ln703_14_fu_208_p2 + add_ln703_7_fu_166_p2);

endmodule //reduce_ap_fixed_16_Op_add_ap_fixed_16_8_5_3_0_s
